#!/usr/bin/env python3
"""cert 07 -- the pair of Hadamard matrices of order 2060, at its honest label.

  CLAIM.  The two order-2060 Hadamard matrices generated by one quadruple of
  length-515 sequences -- '2060-plain', the plain Goethals-Seidel array over
  the raw Z_515 seed, and '2060-gist', the x104-twisted array that is
  byte-for-byte the publicly posted H(2060) -- are inequivalent.

  LABEL.  COMPUTATIONAL-EVIDENCE.  **NOT A PROOF, and this certificate does
  not write it as one.**  A sampled 4-profile can corroborate a separation;
  it can never establish one.  What is actually in hand:

    * every EXACT invariant computed on the pair AGREES (dim W on both
      sides, recomputed here from scratch; and, in the lab that produced
      these matrices, the row- and column-pair collision profiles and the
      exhaustively enumerated strata |T4| >= 2056, all empty on both);
    * the SAMPLED |T4| 4-profiles differ systematically -- row side
      max |d| = 7.4 with 21 bins over d = 4, column side 7.1 with 13,
      where d = |p - q| / sqrt(p + q) is a RAW STANDARDIZED DELTA (a
      heuristic z-score under an unpaired Poisson common-mean
      approximation) and NOT a calibrated sigma: the draws are PAIRED
      (one common seed, the same 4-subset sequence on both matrices),
      the denominator is the unpaired variance, the per-bin discordance
      counts a paired variance would need were not banked, and no
      multiplicity control is applied across the bins scanned -- yet the
      pattern is reproducible, coherent and monotone across consecutive
      bins, and the SIGN of every resolved bin difference is reproduced
      by a second, independent sampler with a different RNG and seed;
    * the block-affine equivalence family is EXHAUSTED with no solution
      (a bounded negative search: it closes that family and nothing else).

  Sampled profiles cannot prove inequivalence; every exact invariant
  computed agrees; the block-affine family is exhausted.  That sentence is
  the whole claim.

  THE UPGRADE HOOK.  The one computation that would turn this into a
  theorem is the EXACT |T4| 4-profile at 2060 -- all C(2060,4) row
  4-subsets, the same invariant that settles order 668 in cert 06.  It is
  priced, not impossible: about 11-22 core-hours for the pair, the binding
  constraint being memory (the pair-vector matrix is 2 120 770 x 2060).
  A run is in progress in the source lab under a written pre-registration.

  Cashing it in is ALL-OR-NOTHING.  The bank is exactly the four files
  data/sep2060-exact-{blas,bits}-{plain,gist}.json, each in the versioned
  schema "sep2060-exact-profile/1" and each naming the canonical SHA-256
  of the matrix THIS SCRIPT rebuilds for its tag.  Anything else -- an
  unknown name matching the glob, a duplicate, a partial set, a malformed
  file, a file bound to the wrong matrix, blas and bits disagreeing -- is
  a HARD FAILURE (exit 1).  A partial bank is an ERROR STATE, not an
  absence, and never falls back to the sampled path.  With no such file
  present at all the honest sampled mode runs, unchanged.  The banking
  helper is bank_exact.py; the procedure is in NOTES.md.

  WHAT EXACT MODE DOES AND DOES NOT SHOW.  It AUDITS a banked profile and
  binds it to a DECLARED matrix identity.  A self-declared digest is not
  proof of computation.  The proof of computation is the producer's
  registered run.  --selftest exercises exactly that boundary: the
  fabricated profiles that satisfy every numeric identity are rejected
  for want of schema and binding, and a well-formed bound bank is
  accepted -- so the gate is shown to close AND to open.

WHAT THIS SCRIPT DOES  (standard library only, no numpy anywhere, seconds)

  (1) Rebuilds both matrices from data/sep2060-records.json -- the minimal
      banked inputs, seeds spelled out and every convention stated -- hands
      each to verify/verify.py (the trust chain), compares the canonical
      SHA-256 against the pins below, and DELETES the generated matrices.
  (2) Recomputes dim V and dim W over F2 on both matrices, both sides,
      from the rebuilt rows: an exact invariant that AGREES, recorded so
      the "every exact invariant agrees" clause is measured here and not
      merely cited.
  (3) Chooses its mode: EXACT if any data/sep2060-exact-*.json is present
      (and then the bank must be complete and well formed, or the run
      FAILS), SAMPLED-EVIDENCE if none is.
  (4) SAMPLED mode: loads data/sep2060-sampled-histograms.json, asserts the
      fold guard (no negative bin anywhere -- signed T4 is NOT an
      invariant), validates every total against the declared sample size,
      recomputes every per-bin standardized delta d between plain and gist,
      and asserts that max |d| and the count of bins with d > 4 reproduce
      the banked expectations to the digit.
      EXACT mode: bank acceptance (exactly four expected basenames,
      versioned schema, every field typed and checked, matrix binding
      against the digests rebuilt in clause 1) and then the cert-06 audit
      chain -- bins = n (mod 8), total = C(2060,4), second moment =
      n^3(n-1)(n-2)/24, blas == bits bin for bin -- then the profile
      comparison, and the verdict PROVEN-BY-CERTIFICATE.
  (5) Controls:
        C1  the fold guard, stated and checked on every banked histogram;
        C2  the SIGNED-T4 trap, demonstrated EXACTLY on a small Hadamard
            matrix: a legal signed row negation moves the signed T4
            profile and leaves the |T4| profile fixed.  This is why every
            histogram in this repository is folded at measurement;
        C3  d-statistic calibration: a histogram against itself reads
            max |d| = 0 with zero bins over d = 4;
        C4  the blindness calibration, and it is the important one.  The
            SAME sampled statistic, at the SAME budget, is run on the 668
            pair -- which cert 06 PROVES inequivalent -- and reads
            max |d| = 1.8 with ZERO bins over d = 4.  A null sampled
            reading is therefore worth nothing at all, and a positive one
            is evidence and not proof.  That is the calibration that
            fixes this certificate's label;
        C5  cross-sampler corroboration: for every bin the 20 000 000-draw
            sampler resolves past d = 4, the independent 3 000 000-draw
            sampler must agree on the SIGN of the difference.  Its own
            max |d| is reported honestly: at its smaller budget it does
            NOT resolve the separation, exactly as sqrt(N) predicts.

Usage:
  python certs/07-2060-evidence/run.py
  python certs/07-2060-evidence/run.py --selftest
"""

import argparse
import glob
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import time

sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

N = 2060
V = 515
OUT = os.path.join(HERE, "out")

# Canonical digests, pinned by earlier and independent parts of the record:
# the plain GS array and the gist were both measured before this repository
# existed, and the gist digest is additionally the digest of the publicly
# posted artifact itself.
SHA_PLAIN = \
    "510f89b7b423c85da0c7cada52cb0f62e0415d736d2040d6701f66c4e524cf6a"
SHA_GIST = \
    "c7a145d86210740dd3f8ea21ca896a54d6916007a042638f17c8c47f097200f7"

FILE_PINS = {
    "data/sep2060-records.json":
        "1c9742fe485f5cc7232c2e876d322ca0094270bc40e537d16da422c0a13202bc",
    "data/sep2060-sampled-histograms.json":
        "586d9fe51a4c24448dd44efbe1e3e60a3ec0c83167e263fb008f538efe2ecdc8",
    "data/sep668-sampled-histograms.json":
        "a21973871c0ad80a8a3b95e057066ae72710194a3638ce3228c647ce502804a6",
}

FAIL = []
FLIP = str.maketrans("+-", "-+")


def check(label, cond, extra=""):
    print("  [%s] %s%s" % ("PASS" if cond else "FAIL", label,
                           ("  " + extra) if extra else ""))
    if not cond:
        FAIL.append(label)
    return cond


def rel(p):
    return os.path.relpath(p, ROOT).replace("\\", "/")


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def rows_sha256(rows):
    h = hashlib.sha256()
    for r in rows:
        h.update((r + "\n").encode("ascii"))
    return h.hexdigest()


def c_n_4(n):
    return n * (n - 1) * (n - 2) * (n - 3) // 24


def second_moment_want(n):
    """sum over 4-subsets of T4^2 = n^3 (n-1)(n-2) / 24  (NOTE-B.md S3.1)."""
    return n ** 3 * (n - 1) * (n - 2) // 24


# The two order-2060 identities every exact profile must satisfy -- the
# cert-06 audit chain -- are checked inside validate_blob() below, which
# reports WHICH one failed rather than raising a bare AssertionError.


# ======================================================================
# the EXACT bank: what a cash-in must look like before it is believed
#
# Exact banking is ALL-OR-NOTHING.  The bank is exactly four files, one
# per (impl, tag); every field is typed and checked; every file names the
# canonical digest of the matrix this script rebuilt for its tag.  A file
# that matches the glob and fails any of this is an ERROR STATE, not an
# absence: the cert fails closed and does NOT fall back to sampled mode.
#
# What this layer establishes: the bank is complete, well formed,
# internally consistent, arithmetically consistent with the order-2060
# identities, agreed between two implementations, and DECLARES the matrix
# this script rebuilt.  What it does NOT establish: that the counts were
# computed from that matrix.  A self-declared digest is not proof of
# computation.  The proof of computation is the producer's registered run
# (NOTES.md, "The cash-in procedure").
# ======================================================================

SCHEMA = "sep2060-exact-profile/1"
IMPLS = ("blas", "bits")
TAGS = ("plain", "gist")
EXACT_GLOB = "sep2060-exact-*.json"


def exact_basename(impl, tag):
    return "sep2060-exact-%s-%s.json" % (impl, tag)


EXPECTED_BANK = dict(((exact_basename(i, t), (i, t))
                      for i in IMPLS for t in TAGS))

REQUIRED_FIELDS = ("schema", "n", "tag", "impl", "matrix_canonical_sha256",
                   "producer", "profile", "total", "second_moment")
OPTIONAL_FIELDS = ("producer_matrix_sha256", "source_file", "banked_utc",
                   "seconds", "engine", "enumeration", "folded", "q",
                   "threads", "geom", "peak_rss_mb", "note")

# Filled only after a controlled generation has produced the four files.
# While it is empty no file digest is pinned; a name present here is
# checked against the file on disk before the bank is read.  It is
# all-or-nothing: empty, or exactly the four expected basenames -- see
# validate_pin_coverage below.
EXACT_FILE_PINS = {}

HEXDIGITS = set("0123456789abcdef")


class BankError(Exception):
    """A refusal to accept an exact bank.  .reason is a stable code."""

    def __init__(self, reason, detail):
        Exception.__init__(self, "%s -- %s" % (reason, detail))
        self.reason = reason
        self.detail = detail


def is_int(x):
    return isinstance(x, int) and not isinstance(x, bool)


def is_sha256(s):
    return isinstance(s, str) and len(s) == 64 and set(s) <= HEXDIGITS


def select_bank(paths):
    """Exactly the four expected basenames: no unknowns, no duplicates,
    no partial set.  Returns [(impl, tag, path)] in basename order."""
    seen = {}
    for p in paths:
        b = os.path.basename(p)
        if b not in EXPECTED_BANK:
            raise BankError(
                "unknown-basename",
                "%s matches %s but is not one of the four expected files "
                "(%s)" % (b, EXACT_GLOB, ", ".join(sorted(EXPECTED_BANK))))
        if b in seen:
            raise BankError("duplicate-basename",
                            "%s is presented more than once" % b)
        seen[b] = p
    missing = sorted(set(EXPECTED_BANK) - set(seen))
    if missing:
        raise BankError(
            "partial-set",
            "exact banking is all-or-nothing; %d of 4 files present, "
            "missing %s" % (len(seen), ", ".join(missing)))
    return [(EXPECTED_BANK[b][0], EXPECTED_BANK[b][1], seen[b])
            for b in sorted(seen)]


def parse_profile(raw, where):
    """The profile object -> {int bin: int count}, or a refusal."""
    if not isinstance(raw, dict) or not raw:
        raise BankError("profile-key",
                        "%s: profile is not a non-empty object" % where)
    prof = {}
    for k, v in raw.items():
        if not isinstance(k, str):
            raise BankError("profile-key",
                            "%s: bin key %r is not a string" % (where, k))
        try:
            ik = int(k)
        except ValueError:
            raise BankError("profile-key",
                            "%s: bin key %r is not an integer" % (where, k))
        if str(ik) != k:
            raise BankError(
                "profile-key",
                "%s: bin key %r is not in canonical decimal form" % (where, k))
        if ik < 0 or ik > N:
            raise BankError("profile-key",
                            "%s: bin |T4| = %d is outside [0, %d]"
                            % (where, ik, N))
        if ik % 8 != N % 8:
            raise BankError("profile-key",
                            "%s: bin |T4| = %d is not = %d (mod 8)"
                            % (where, ik, N % 8))
        if not is_int(v):
            raise BankError("profile-count",
                            "%s: the count for bin %d is not an integer"
                            % (where, ik))
        if v <= 0:
            raise BankError(
                "profile-count",
                "%s: bin %d has count %d; counts must be positive (no "
                "negative counts, no zero-count bins)" % (where, ik, v))
        prof[ik] = v
    return prof


def validate_blob(blob, impl, tag, digest, where):
    """One bank file, against the schema and against the rebuilt matrix."""
    if not isinstance(blob, dict):
        raise BankError("field-type", "%s: top level is not an object" % where)
    for f in REQUIRED_FIELDS:
        if f not in blob:
            raise BankError("field-missing",
                            "%s: no %r field" % (where, f))
    extra = sorted(set(blob) - set(REQUIRED_FIELDS) - set(OPTIONAL_FIELDS))
    if extra:
        raise BankError("unknown-field",
                        "%s: unrecognised field(s) %s"
                        % (where, ", ".join(extra)))
    if blob["schema"] != SCHEMA:
        raise BankError("schema", "%s: schema is %r, want %r"
                        % (where, blob["schema"], SCHEMA))
    if not is_int(blob["n"]) or blob["n"] != N:
        raise BankError("n", "%s: n is %r, want %d" % (where, blob["n"], N))
    if blob["tag"] != tag:
        raise BankError("tag", "%s: declares tag %r, the filename says %r"
                        % (where, blob["tag"], tag))
    if blob["impl"] != impl:
        raise BankError("impl", "%s: declares impl %r, the filename says %r"
                        % (where, blob["impl"], impl))
    if not isinstance(blob["producer"], str) or not blob["producer"].strip():
        raise BankError("producer",
                        "%s: producer is not a non-empty string" % where)
    dec = blob["matrix_canonical_sha256"]
    if not is_sha256(dec):
        raise BankError("matrix-binding",
                        "%s: matrix_canonical_sha256 is not a lowercase "
                        "hex SHA-256" % where)
    if not is_sha256(digest):
        raise BankError("matrix-binding",
                        "%s: no rebuilt digest is available for tag %r"
                        % (where, tag))
    if dec != digest:
        raise BankError(
            "matrix-binding",
            "%s: declares matrix %s..., but the %s matrix rebuilt by this "
            "script is %s..." % (where, dec[:16], tag, digest[:16]))
    pm = blob.get("producer_matrix_sha256")
    if pm is not None and pm != digest:
        raise BankError(
            "matrix-binding",
            "%s: producer_matrix_sha256 %s... != the rebuilt %s matrix %s..."
            % (where, str(pm)[:16], tag, digest[:16]))
    prof = parse_profile(blob["profile"], where)
    if not is_int(blob["total"]) or not is_int(blob["second_moment"]):
        raise BankError("field-type",
                        "%s: total / second_moment are not integers" % where)
    tot = sum(prof.values())
    if tot != blob["total"]:
        raise BankError("profile-total",
                        "%s: declares total %d, the bins sum to %d"
                        % (where, blob["total"], tot))
    if tot != c_n_4(N):
        raise BankError("profile-total",
                        "%s: total %d, want C(%d,4) = %d"
                        % (where, tot, N, c_n_4(N)))
    m2 = sum(k * k * v for k, v in prof.items())
    if m2 != blob["second_moment"]:
        raise BankError("profile-second-moment",
                        "%s: declares second moment %d, the bins give %d"
                        % (where, blob["second_moment"], m2))
    if m2 != second_moment_want(N):
        raise BankError("profile-second-moment",
                        "%s: sum T4^2 = %d, want n^3(n-1)(n-2)/24 = %d"
                        % (where, m2, second_moment_want(N)))
    return prof


def json_loader(path):
    """Read one bank file.  A truncated, non-ASCII or syntactically invalid
    file is a REFUSAL, not a traceback: run_exact handles BankError and
    prints the remediation, so the read has to fail in that currency."""
    try:
        with open(path, "r", encoding="ascii") as fh:
            return json.load(fh)
    except (ValueError, OSError) as e:
        raise BankError("malformed-file",
                        "%s: unreadable or not well-formed JSON -- %s: %s"
                        % (os.path.basename(path), type(e).__name__, e))


def accept_bank(paths, digests, loader=json_loader):
    """THE ACCEPTANCE PREDICATE.  Returns {(tag, impl): profile} or raises
    BankError.  `loader` is injectable so --selftest can exercise this
    entirely in memory, writing nothing."""
    prof = {}
    for impl, tag, path in select_bank(paths):
        try:
            blob = loader(path)
        except BankError:
            raise
        except (ValueError, OSError) as e:
            raise BankError("malformed-file",
                            "%s: unreadable or not well-formed JSON -- %s: %s"
                            % (os.path.basename(path), type(e).__name__, e))
        prof[(tag, impl)] = validate_blob(blob, impl, tag,
                                          digests.get(tag),
                                          os.path.basename(path))
    for tag in TAGS:
        a, b = prof[(tag, "blas")], prof[(tag, "bits")]
        if a != b:
            k = sorted(set(a) | set(b))
            bad = [x for x in k if a.get(x, 0) != b.get(x, 0)][0]
            raise BankError(
                "impl-disagreement",
                "%s: blas and bits differ at |T4| = %d (%d vs %d) -- "
                "registration kill criterion 5" % (tag, bad, a.get(bad, 0),
                                                   b.get(bad, 0)))
    return prof


def validate_pin_coverage(pins):
    """EXACT_FILE_PINS is all-or-nothing: either empty -- no byte pinning,
    and the cert says so -- or exactly the four expected basenames.  A dict
    naming three of the four would print three pin lines, raise no warning,
    and leave the fourth file unpinned and freely editable."""
    if not pins:
        return
    missing = sorted(set(EXPECTED_BANK) - set(pins))
    extra = sorted(set(pins) - set(EXPECTED_BANK))
    if missing or extra:
        raise BankError("pin-coverage",
                        "EXACT_FILE_PINS is non-empty but is not exactly the "
                        "four expected basenames: missing %s, unexpected %s"
                        % (missing or "none", extra or "none"))


# ======================================================================
# the assembly -- stdlib strings, exactly the conventions banked in
# data/sep2060-records.json
# ======================================================================

def circ(sq):
    """circ(x)[i][j] = x[(i - j) mod v]."""
    v = len(sq)
    r0 = "".join(sq[(-j) % v] for j in range(v))
    return [r0[v - i:] + r0[:v - i] for i in range(v)]


def rev_seq(sq):
    v = len(sq)
    return "".join(sq[(-k) % v] for k in range(v))


def twist(sq, k):
    """twist(x, k)[i][j] = circ(x)[i][(k*j) mod v] -- the multiplier twist."""
    v = len(sq)
    sig = [(k * j) % v for j in range(v)]
    return ["".join(row[t] for t in sig) for row in circ(sq)]


def neg(rs):
    return [r.translate(FLIP) for r in rs]


def mulJ(rs):
    return [r[::-1] for r in rs]


def conjJ(rs):
    return [r[::-1] for r in rs[::-1]]


def relabel(rs, inv):
    return ["".join(rs[i][t] for t in inv) for i in inv]


def grid_rows(grid, v):
    out = []
    for r in range(4):
        b0, b1, b2, b3 = grid[r]
        for p in range(v):
            out.append(b0[p] + b1[p] + b2[p] + b3[p])
    return out


def build_2060(recs):
    """Both order-2060 arrays from the banked seed.  Returns (plain, gist)."""
    ns = recs["normalised_seed"]
    e = list(recs["normalising_shifts"])
    raw = ["".join(ns[q][(u + e[q]) % V] for u in range(V)) for q in range(4)]
    a, b, c, d = raw

    A = circ(a)
    Bj, Cj, Dj = mulJ(circ(b)), mulJ(circ(c)), mulJ(circ(d))
    Bt, Ct, Dt = (mulJ(circ(rev_seq(b))), mulJ(circ(rev_seq(c))),
                  mulJ(circ(rev_seq(d))))
    plain = [[A, Bj, Cj, Dj],
             [neg(Bj), A, Dt, neg(Ct)],
             [neg(Cj), neg(Dt), A, Bt],
             [neg(Dj), Ct, neg(Bt), A]]

    k = int(recs["gist_array"]["twist"])
    A_ = circ(a)
    B_, C_, D_ = mulJ(twist(b, k)), mulJ(twist(c, k)), mulJ(twist(d, k))
    X12, X13, X23 = neg(conjJ(D_)), conjJ(C_), neg(conjJ(B_))
    tw = [[A_, B_, C_, D_],
          [neg(B_), A_, X12, X13],
          [neg(C_), neg(X12), A_, X23],
          [neg(D_), neg(X13), neg(X23), A_]]
    ORD = [5 * (g % 103) + (g % 5) for g in range(V)]   # the CRT relabelling
    inv = [0] * V
    for g in range(V):
        inv[ORD[g]] = g
    tw = [[relabel(blk, inv) for blk in row] for row in tw]
    return grid_rows(plain, V), grid_rows(tw, V), raw


def verify_rows(tag, rows, want_sha):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, "H2060_%s.txt" % tag)
    with open(path, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(rows) + "\n")
    proc = subprocess.run(
        [sys.executable, os.path.join(ROOT, "verify", "verify.py"), path],
        capture_output=True, text=True)
    verdict = ((proc.stdout or proc.stderr).strip().splitlines()
               or ["(no output)"])[-1]
    check("%-5s verify/verify.py" % tag, proc.returncode == 0, verdict[:76])
    dig = rows_sha256(rows)
    check("%-5s canonical sha256 == pin" % tag, dig == want_sha,
          dig[:24] + "...")
    check("%-5s verify.py reports the same digest" % tag, dig in verdict)
    os.remove(path)
    return dig


# ======================================================================
# F2 difference code
# ======================================================================

def f2_rank(vectors):
    """Rank over F2 by highest-set-bit pivoting.  Exact, no floats."""
    piv = {}
    r = 0
    for v in vectors:
        while v:
            h = v.bit_length() - 1
            if h in piv:
                v ^= piv[h]
            else:
                piv[h] = v
                r += 1
                break
    return r


def dim_V_W(rows):
    """V = span{r_i + r_j} = span{r_i + r_0}; W = V + <all-ones>.

    Only dim W is a Hadamard-equivalence invariant: row negation sends
    r_i -> r_i + delta_i*1, so the stray all-ones terms live in W but move
    V.  See NOTE-B.md S3.1 trap 1, and cert 06 control C3, which exhibits
    the jump.
    """
    n = len(rows)
    f = []
    for r in rows:
        v = 0
        for c, ch in enumerate(r):
            if ch == "-":
                v |= 1 << c
        f.append(v)
    gens = [f[i] ^ f[0] for i in range(1, n)]
    ones = (1 << len(rows[0])) - 1
    return f2_rank(gens), f2_rank(gens + [ones])


# ======================================================================
# the standardized delta -- the lab's summarize.py statistic, restated
# exactly, and named for what it is
# ======================================================================

def z_table(HA, HB, floor=200):
    """Per-bin RAW STANDARDIZED DELTA between two histograms of EQUAL
    sample size:  d = |p - q| / sqrt(p + q).

    Read it as a heuristic z-score, NOT as a calibrated sigma.  The
    denominator is the UNPAIRED Poisson/common-mean approximation: if both
    counts were independent and Poisson around e = (p+q)/2 then
    Var(p - q) = 2e and d = |p - q| / sqrt(2e) = |p - q| / sqrt(p + q).

    THE SAMPLING DESIGN IS NOT THAT.  Upstream (Hadamard-2060,
    experiments/inequiv/inv_a.py and inv_b.py) each implementation draws
    its 4-subsets from random.Random(seed) with ONE seed -- 20260831 for A,
    831026 for B -- and the draw stream depends only on the seed and on n,
    which is 2060 for both matrices.  The SAME sequence of 4-subsets is
    therefore evaluated on plain and on gist: the comparison is PAIRED
    (the source lab records this as "common seed (so the comparison is
    paired)", intel/inequivalence-2026-08-31.md S4.4).  A paired variance
    is Var(p) + Var(q) - 2 Cov(p, q), and computing it needs the per-bin
    DISCORDANCE counts -- how many drawn 4-subsets land in bin k for one
    matrix and not the other.  Those were not banked, so the paired
    variance cannot be recovered from this bank and the unpaired
    denominator is what is reported.

    No multiplicity control is applied.  The scan compares 28 bins on each
    A side and 25 / 24 on the B sides -- 105 per-bin comparisons -- and the
    reported max |d| is a maximum over them, not a single pre-registered
    test.

    This is why the label on this certificate is COMPUTATIONAL-EVIDENCE and
    why control C4 (not the size of d) is what fixes it.  Bins with
    p + q < floor are not compared: the normal approximation is not
    trustworthy there and the sampler cannot resolve them anyway.
    """
    rows = []
    for k in sorted(set(HA) | set(HB)):
        p, q = HA.get(k, 0), HB.get(k, 0)
        if p + q < floor:
            continue
        rows.append((k, p, q, abs(p - q) / math.sqrt(p + q)))
    return rows


def summarise(rows):
    if not rows:
        return 0.0, None, 0, 0
    worst = max(rows, key=lambda t: t[3])
    return worst[3], worst[0], sum(1 for t in rows if t[3] > 4), len(rows)


def as_int_hist(d):
    return {int(k): int(v) for k, v in d.items()}


def load_hists(path):
    with open(path, "r", encoding="ascii") as fh:
        blob = json.load(fh)
    H = {k: as_int_hist(v) for k, v in blob["histograms"].items()}
    return blob, H


# ======================================================================
# controls
# ======================================================================

def sylvester(k):
    n = 1 << k
    return ["".join("+" if bin(x & y).count("1") % 2 == 0 else "-"
                    for y in range(n)) for x in range(n)]


GS7 = ["+------", "+++----", "++--+--", "+-+-+--"]      # -> H(28), 3 bins


def gs28():
    """The same plain GS array over Z_7 cert 06 uses as a control."""
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    import bordered_gs as BGS
    xs = [BGS.signs(s) for s in GS7]
    G = BGS.AbelianGroup([7])
    return BGS.assemble(G, xs, G.sub_table(), G.idx((6,)), 0, 1,
                        [0] * 7, None, None, None)


def is_hadamard(rows):
    n = len(rows)
    S = [[1 if ch == "+" else -1 for ch in r] for r in rows]
    if any(len(r) != n for r in S):
        return False
    for i in range(n):
        for j in range(i + 1, n):
            if sum(a * b for a, b in zip(S[i], S[j])) != 0:
                return False
    return True


def signed_and_abs_profile(rows):
    """(signed T4 histogram, |T4| histogram), by straight enumeration."""
    n = len(rows)
    S = [[1 if ch == "+" else -1 for ch in r] for r in rows]
    sg, ab = {}, {}
    for a in range(n):
        for b in range(a + 1, n):
            ab2 = [S[a][c] * S[b][c] for c in range(n)]
            for c_ in range(b + 1, n):
                abc = [ab2[c] * S[c_][c] for c in range(n)]
                for d in range(c_ + 1, n):
                    t = sum(abc[c] * S[d][c] for c in range(n))
                    sg[t] = sg.get(t, 0) + 1
                    ab[abs(t)] = ab.get(abs(t), 0) + 1
    return sg, ab


# ======================================================================
# main
# ======================================================================

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--selftest", action="store_true",
                    help="exercise the exact-bank acceptance predicate "
                         "in memory (negative controls and a positive "
                         "control) and exit; writes nothing")
    args = ap.parse_args(argv)
    if args.selftest:
        return selftest()
    t_start = time.time()

    print("=" * 74)
    print("cert 07 -- order 2060: two arrays from one seed, at their honest "
          "label")
    print("=" * 74)

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)

    try:
        # ------------------------------------------------------ clause 0
        print("\n[0] banked data files, SHA-256 pinned in this script")
        for name, want in sorted(FILE_PINS.items()):
            got = file_sha256(os.path.join(ROOT, name))
            check("%-40s" % name, got == want, got[:24] + "...")

        # ------------------------------------------------------ clause 1
        print("\n[1] rebuild both order-2060 matrices, verify, pin")
        with open(os.path.join(ROOT, "data", "sep2060-records.json"),
                  "r", encoding="ascii") as fh:
            recs = json.load(fh)
        t0 = time.time()
        plain, gist, raw = build_2060(recs)
        print("      assembled 2 x %d x %d cells from one length-%d quadruple "
              "in %.1fs" % (N, N, V, time.time() - t0))
        check("the banked seed reproduces the banked row sums",
              [sum(1 if ch == "+" else -1 for ch in x) for x in raw]
              == list(recs["row_sums"]), str(recs["row_sums"]))
        check("the two arrays are genuinely different matrices",
              plain != gist, "same seed, different array orientation")
        # The digests OUTLIVE the matrices: exact mode binds every banked
        # profile to the matrix rebuilt here, so these must not be dropped
        # with the rows.
        digests = {"plain": verify_rows("plain", plain, SHA_PLAIN),
                   "gist": verify_rows("gist", gist, SHA_GIST)}

        # ------------------------------------------------------ clause 2
        print("\n[2] an EXACT invariant, recomputed here: dim W over F2")
        dims = {}
        for tag, rows in (("plain", plain), ("gist", gist)):
            t0 = time.time()
            dims[(tag, "row")] = dim_V_W(rows)
            cols = ["".join(c) for c in zip(*rows)]
            dims[(tag, "col")] = dim_V_W(cols)
            del cols
            print("      %-5s  row (dim V %d, dim W %d)   col (dim V %d, "
                  "dim W %d)   (%.1fs)"
                  % (tag, dims[(tag, "row")][0], dims[(tag, "row")][1],
                     dims[(tag, "col")][0], dims[(tag, "col")][1],
                     time.time() - t0))
        check("dim W (INVARIANT) agrees on both sides -- it does NOT separate",
              dims[("plain", "row")][1] == dims[("gist", "row")][1]
              and dims[("plain", "col")][1] == dims[("gist", "col")][1],
              "row %d, col %d" % (dims[("plain", "row")][1],
                                  dims[("plain", "col")][1]))
        check("dim V (not an invariant) happens to agree too -- also "
              "worthless",
              dims[("plain", "row")][0] == dims[("gist", "row")][0]
              and dims[("plain", "col")][0] == dims[("gist", "col")][0],
              "a matching invariant is never evidence of equivalence")
        del plain, gist

        # ------------------------------------------------------ clause 3
        exact_files = sorted(glob.glob(os.path.join(ROOT, "data",
                                                    EXACT_GLOB)))
        print("\n[3] mode")
        print("      data/%s: %s"
              % (EXACT_GLOB, ", ".join(os.path.basename(f)
                                       for f in exact_files)
                 if exact_files else "not present"))
        if exact_files:
            print("      -> EXACT: a cash-in is present, so it is audited "
                  "all-or-nothing.")
            print("         A partial or malformed bank FAILS here; it does "
                  "not fall back.")
            rc = run_exact(exact_files, digests)
        else:
            print("      -> SAMPLED-EVIDENCE (the honest fallback)")
            rc = run_sampled()
    finally:
        shutil.rmtree(OUT, ignore_errors=True)

    print("\ngenerated matrices deleted; nothing left in %s   (%.1fs total)"
          % (rel(OUT), time.time() - t_start))
    return rc


# ---------------------------------------------------------------- EXACT
def run_exact(exact_files, digests, loader=json_loader):
    """Bank acceptance, then the cert-06 audit chain, applied at 2060.
    Reached only when at least one file matches the exact glob -- and from
    that point the bank is all-or-nothing: every refusal below is a hard
    FAIL, never a fall-back to the sampled path."""
    print("\n[4] the EXACT 4-profiles: bank acceptance, then the audit chain")

    try:
        validate_pin_coverage(EXACT_FILE_PINS)
        if EXACT_FILE_PINS:
            for path in exact_files:
                base = os.path.basename(path)
                if base in EXACT_FILE_PINS and os.path.exists(path):
                    got = file_sha256(path)
                    check("%-34s sha256 == pin" % base,
                          got == EXACT_FILE_PINS[base], got[:24] + "...")
        prof = accept_bank(exact_files, digests, loader)
    except BankError as e:
        check("the exact bank is complete, well formed and bound to the "
              "rebuilt matrices", False, "%s -- %s" % (e.reason, e.detail))
        print("\n      Exact banking is ALL-OR-NOTHING.  A partial or")
        print("      malformed exact bank is an ERROR STATE, not an absence:")
        print("      this certificate does NOT fall back to the sampled path")
        print("      while one is present.  Either remove every")
        print("      data/%s to return to the honest sampled" % EXACT_GLOB)
        print("      mode, or re-bank all four files with")
        print("      certs/07-2060-evidence/bank_exact.py.")
        print("\n" + "=" * 74)
        print("cert 07: FAIL (%d): %s" % (len(FAIL), FAIL))
        print("=" * 74)
        return 1

    check("the exact bank is exactly the four expected files, schema %s, "
          "every field checked" % SCHEMA, True,
          ", ".join(sorted(EXPECTED_BANK)))
    for tag in TAGS:
        for impl in IMPLS:
            p = prof[(tag, impl)]
            check("%-5s %-4s  %3d bins, all |T4| = %d (mod 8), total == "
                  "C(2060,4), second moment == %d"
                  % (tag, impl, len(p), N % 8, second_moment_want(N)), True)
        check("%-5s       blas == bits, bin for bin (two independent "
              "implementations)" % tag, True,
              "%d bins" % len(prof[(tag, "blas")]))
        check("%-5s       every banked file names the matrix rebuilt in "
              "clause 1" % tag, True, digests[tag][:24] + "...")

    # blas is the registered primary; bits agreed with it bin for bin above.
    A = prof[("plain", "blas")]
    B = prof[("gist", "blas")]
    ks = sorted(set(A) | set(B))
    diff = [(k, A.get(k, 0), B.get(k, 0)) for k in ks
            if A.get(k, 0) != B.get(k, 0)]
    check("the differences sum to zero", sum(q - p for _k, p, q in diff) == 0)
    print("\n      support: plain %d bins, gist %d bins, union %d"
          % (len(A), len(B), len(ks)))
    print("      %d of %d bins differ" % (len(diff), len(ks)))
    for k, p, q in diff[:60]:
        print("      %6d %18d %18d %+14d" % (k, p, q, q - p))
    print("\n" + "=" * 74)
    if diff and not FAIL:
        print("VERDICT: 2060-plain and 2060-gist are Hadamard-INEQUIVALENT.")
        print("         Separating invariant: the exact |T4| 4-profile over")
        print("         all C(2060,4) = %d row 4-subsets." % c_n_4(N))
        print("         LABEL: PROVEN-BY-CERTIFICATE.")
        print()
        print("         SCOPE OF THIS CERTIFICATE.  It AUDITS a banked exact")
        print("         profile and binds it to the matrix rebuilt here by a")
        print("         DECLARED digest.  It does not recompute the profile,")
        print("         and a self-declared digest is not proof of")
        print("         computation.  The recompute path is the producer's")
        print("         registered run -- see NOTES.md, 'The cash-in")
        print("         procedure'.")
    elif not diff:
        print("The exact 4-profiles are IDENTICAL.  That is NOT equivalence:")
        print("a matching invariant never proves two matrices are the same.")
        print("The claim of this certificate is withdrawn to UNDECIDED and")
        print("NOTE-B.md must be corrected before anything is published.")
        FAIL.append("exact profiles identical -- claim withdrawn")
    print("=" * 74)
    if FAIL:
        print("cert 07: FAIL (%d): %s" % (len(FAIL), FAIL))
        return 1
    return 0


# -------------------------------------------------------------- SAMPLED
def run_sampled():
    print("\n[4] the banked sampled |T4| histograms")
    blob, H = load_hists(os.path.join(ROOT, "data",
                                      "sep2060-sampled-histograms.json"))
    exp = blob["expected"]
    prov = blob["provenance"]

    print("      impl A: %s draws/matrix/side, seed %s, %s"
          % (prov["impl_A"]["samples_per_matrix_per_side"],
             prov["impl_A"]["rng_seed"],
             "FOLDED from the legacy SIGNED key"
             if prov["impl_A"]["folded_from_legacy"] else "native |T4|"))
    print("      impl B: %s draws/matrix/side, seed %s, %s"
          % (prov["impl_B"]["samples_per_matrix_per_side"],
             prov["impl_B"]["rng_seed"],
             "FOLDED from the legacy SIGNED key"
             if prov["impl_B"]["folded_from_legacy"] else "native |T4|"))

    # C1 -- the fold guard
    print("\n  C1 -- the fold guard, on every banked histogram")
    neg_bins = [k for h in H.values() for k in h if k < 0]
    check("C1  no negative bin anywhere in the bank (SIGNED T4 is NOT an "
          "invariant)", not neg_bins)
    check("C1  every |T4| bin is = %d (mod 8), as it must be at n = %d"
          % (N % 8, N), all(k % 8 == N % 8 for h in H.values() for k in h))
    ok_tot = True
    for key, h in sorted(H.items()):
        impl = key.split("/")[0]
        want = prov["impl_%s" % impl]["samples_per_matrix_per_side"]
        if sum(h.values()) != want:
            ok_tot = False
            check("C1  %s total == declared sample size" % key, False,
                  "%d != %d" % (sum(h.values()), want))
    check("C1  every histogram totals its declared sample size", ok_tot,
          "%d histograms" % len(H))

    # the measurement
    print("\n[5] plain vs gist, per side, per implementation")
    print("      the statistic is d = |p - q| / sqrt(p + q): a RAW")
    print("      STANDARDIZED DELTA, a heuristic z-score under an UNPAIRED")
    print("      Poisson common-mean approximation.  It is not a calibrated")
    print("      sigma.  The design is PAIRED -- one seed per implementation")
    print("      (A %s, B %s) and a draw stream that depends only on the seed"
          % (prov["impl_A"]["rng_seed"], prov["impl_B"]["rng_seed"]))
    print("      and on n, so the SAME 4-subsets are evaluated on both")
    print("      matrices -- and the per-bin discordance counts a paired")
    print("      variance would need were not banked.  No multiplicity")
    print("      control is applied across the bins scanned.  What fixes the")
    print("      label of this certificate is control C4, not the size of d.")
    print("      %-4s %-4s %10s %8s %9s %8s %14s"
          % ("impl", "side", "draws", "bins", "max|d|", "at |T4|", "d > 4"))
    tabs = {}
    for impl in ("A", "B"):
        for side in ("row", "col"):
            rows = z_table(H["%s/plain/%s" % (impl, side)],
                           H["%s/gist/%s" % (impl, side)])
            tabs[(impl, side)] = rows
            mz, at, big, ncmp = summarise(rows)
            e = exp["%s/%s" % (impl, side)]
            print("      %-4s %-4s %10d %8d %9.4f %8s %14d"
                  % (impl, side, e["samples_each"], ncmp, mz, at, big))
            check("      %s/%s reproduces the banked max|d| to the digit"
                  % (impl, side), round(mz, 6) == e["max_abs_z"]
                  and at == e["max_abs_z_at_T4"],
                  "banked %.6f at |T4|=%s (the bank's field is named "
                  "max_abs_z)" % (e["max_abs_z"], e["max_abs_z_at_T4"]))
            check("      %s/%s reproduces the banked count of bins with d > 4"
                  % (impl, side), big == e["bins_over_4sigma"],
                  "banked %d" % e["bins_over_4sigma"])
            check("      %s/%s reproduces the banked bin count compared"
                  % (impl, side), ncmp == e["bins_compared"])

    print("\n      the bins implementation A resolves past d = 4")
    print("      %-4s %6s %12s %12s %10s %8s"
          % ("side", "|T4|", "plain", "gist", "delta", "d"))
    for side in ("row", "col"):
        for k, p, q, z in tabs[("A", side)]:
            if z > 4:
                print("      %-4s %6d %12d %12d %+10d %8.2f"
                      % (side, k, p, q, q - p, z))

    # C2 -- the signed-T4 trap, exactly
    print("\n  C2 -- the SIGNED-T4 trap, demonstrated exactly on GS H(28)")
    rows28 = gs28()
    sg0, ab0 = signed_and_abs_profile(rows28)
    flipped = [(r.translate(FLIP) if i in (0, 3, 11) else r)
               for i, r in enumerate(rows28)]
    sg1, ab1 = signed_and_abs_profile(flipped)
    check("C2  the control is in fact Hadamard, and stays Hadamard after "
          "negating rows {0,3,11}",
          is_hadamard(rows28) and is_hadamard(flipped),
          "a signed row negation is an element of the equivalence group")
    check("C2  the SIGNED T4 profile MOVES -- so it is NOT an invariant",
          sg0 != sg1,
          "signed bins %s -> %s"
          % ({k: sg0[k] for k in sorted(sg0)}, {k: sg1[k] for k in sorted(sg1)}))
    check("C2  the |T4| profile does NOT move -- it is the invariant",
          ab0 == ab1, "%s" % {k: ab0[k] for k in sorted(ab0)})

    # C3 -- calibration on identical data
    print("\n  C3 -- d calibration: a histogram against itself")
    mz, _at, big, _n = summarise(z_table(H["A/plain/row"], H["A/plain/row"]))
    check("C3  max|d| = 0 and zero bins with d > 4 on identical input",
          mz == 0.0 and big == 0)

    # C4 -- the blindness calibration
    print("\n  C4 -- the blindness calibration: the SAME statistic on the")
    print("        668 pair, which cert 06 PROVES inequivalent")
    b6, H6 = load_hists(os.path.join(ROOT, "data",
                                     "sep668-sampled-histograms.json"))
    check("C4  the 668 bank is folded too (no negative bin)",
          not [k for h in H6.values() for k in h if k < 0])
    blind = True
    for impl in ("A", "B"):
        for side in ("row", "col"):
            mz, at, big, ncmp = summarise(
                z_table(H6["%s/decoded/%s" % (impl, side)],
                        H6["%s/twisted/%s" % (impl, side)]))
            e = b6["expected"]["%s/%s" % (impl, side)]
            ok = (round(mz, 6) == e["max_abs_z"]
                  and big == e["bins_over_4sigma"] and ncmp == e["bins_compared"])
            print("        %s/%-4s  %d draws  max|d| = %.2f at |T4| = %s  "
                  "bins d > 4 = %d"
                  % (impl, side, e["samples_each"], mz, at, big))
            if not ok:
                check("C4  668 %s/%s reproduces its bank" % (impl, side), False)
            if big:
                blind = False
    check("C4  the sampled statistic sees NOTHING on a pair that is in fact "
          "inequivalent", blind,
          "zero bins with d > 4 anywhere -> a NULL sampled reading proves "
          "nothing, and a positive one is evidence, never proof")

    # C5 -- cross-sampler corroboration
    print("\n  C5 -- cross-sampler corroboration on the 2060 pair")
    tot_ag, tot_cmp, tot_res = 0, 0, 0
    for side in ("row", "col"):
        Bp, Bg = H["B/plain/%s" % side], H["B/gist/%s" % side]
        ag = cmpd = 0
        for k, p, q, z in tabs[("A", side)]:
            if z <= 4:
                continue
            pb, qb = Bp.get(k, 0), Bg.get(k, 0)
            if pb + qb < 200:
                continue
            cmpd += 1
            if (q - p > 0) == (qb - pb > 0):
                ag += 1
        tot_ag += ag
        tot_cmp += cmpd
        tot_res += sum(1 for t in tabs[("A", side)] if t[3] > 4)
        mzB, _a, bigB, _n = summarise(tabs[("B", side)])
        print("        %s: of the %d bins A resolves, B has %d with enough "
              "mass; sign agrees on %d" % (side, sum(1 for t in tabs[("A", side)]
                                                     if t[3] > 4), cmpd, ag))
        print("             B's own reading at its 6.7x smaller budget: "
              "max|d| = %.2f, %d bins with d > 4" % (mzB, bigB))
    check("C5  two independent samplers, different RNGs and seeds, agree on "
          "the SIGN of the difference in %d of the %d bins A resolves -- the "
          "ones B has enough mass in at its 6.7x smaller budget"
          % (tot_cmp, tot_res), tot_ag == tot_cmp and tot_cmp > 20,
          "%d of %d agree; the other %d resolved bins are NOT compared -- "
          "they are silent, not disagreements" % (tot_ag, tot_cmp,
                                                  tot_res - tot_cmp))
    check("C5  the smaller sampler does NOT resolve the separation, and that "
          "is reported, not hidden", True,
          "d scales as sqrt(N): 7.45 / sqrt(20/3) = %.2f, which is what B "
          "reads" % (7.449633 / math.sqrt(20.0 / 3.0)))

    # ------------------------------------------------------------ verdict
    print("\n" + "=" * 74)
    if FAIL:
        print("cert 07: FAIL (%d): %s" % (len(FAIL), FAIL))
        print("=" * 74)
        return 1
    print("VERDICT: COMPUTATIONAL-EVIDENCE that 2060-plain and 2060-gist are")
    print("         Hadamard-inequivalent.  THIS IS NOT A PROOF.")
    print()
    print("         Sampled profiles cannot prove inequivalence; every exact")
    print("         invariant computed agrees; the block-affine family is")
    print("         exhausted.  The sampled separation is real as a")
    print("         measurement -- raw standardized delta 7.4 on the row")
    print("         side, 21 bins with d > 4, sign-reproduced by an")
    print("         independent sampler -- and C4 shows exactly what such a")
    print("         measurement is worth: on the 668 pair, PROVEN")
    print("         inequivalent, the same statistic reads 1.8 and zero bins.")
    print("         d is a heuristic z-score, not a calibrated sigma: the")
    print("         draws are paired, the denominator is the unpaired")
    print("         variance, and 105 bins were scanned without multiplicity")
    print("         control.  None of that is load-bearing here, because the")
    print("         label is COMPUTATIONAL-EVIDENCE either way.")
    print()
    print("         UPGRADE: bank all four")
    print("         data/sep2060-exact-{blas,bits}-{plain,gist}.json with")
    print("         certs/07-2060-evidence/bank_exact.py and re-run.  The")
    print("         cash-in is all-or-nothing; a partial or unbound bank is a")
    print("         hard failure here, not a fall-back to this mode.")
    print("=" * 74)
    return 0


# ------------------------------------------------------------- SELFTEST
#
# The permanent negative regression.  The profiles below are two
# fabricated profiles with no computational relationship to either matrix.
# They satisfy EVERY numeric identity this certificate checks --
# nonnegative integer counts, every bin = 4 (mod 8), total C(2060,4),
# second moment n^3(n-1)(n-2)/24 -- which is exactly why numeric
# identities alone were never an acceptance criterion.  They are refused
# for want of schema, of a matrix binding, and of a complete four-file
# set.
#
# Everything here runs in memory through an injected loader.  No file is
# read from or written to data/.

FABRICATED = {"plain": {4: 320845991375, 60: 427309705760},
              "gist": {4: 718686062255, 228: 29469634880}}


def _blob(impl, tag, prof, digest):
    """A well-formed bank file, as bank_exact.py would write it."""
    return {"schema": SCHEMA, "n": N, "tag": tag, "impl": impl,
            "matrix_canonical_sha256": digest,
            "producer": "selftest synthetic (not a measurement)",
            "profile": dict((str(k), v) for k, v in sorted(prof.items())),
            "total": sum(prof.values()),
            "second_moment": sum(k * k * v for k, v in prof.items())}


def _bank(digests, profiles=None):
    """The four files, keyed by the path the cert would glob."""
    profiles = profiles or FABRICATED
    out = {}
    for impl in IMPLS:
        for tag in TAGS:
            base = exact_basename(impl, tag)
            out[os.path.join(ROOT, "data", base)] = _blob(
                impl, tag, profiles[tag], digests[tag])
    return out


def _refused(bank, digests, want_reason):
    """Run the acceptance predicate over an in-memory bank."""
    paths = sorted(bank)

    def loader(p):
        return json.loads(json.dumps(bank[p]))       # a fresh copy, no I/O

    try:
        accept_bank(paths, digests, loader)
    except BankError as e:
        return e.reason == want_reason, "refused: %s -- %s" % (e.reason,
                                                               e.detail)
    return False, "ACCEPTED -- the gate did not close"


def selftest():
    print("=" * 74)
    print("cert 07 --selftest: the exact-bank acceptance predicate")
    print("=" * 74)
    print("\nEverything below runs in memory through an injected loader.")
    print("No file is written; data/ is not touched; no verdict is printed.")

    print("\n[0] the matrices, rebuilt for their canonical digests")
    with open(os.path.join(ROOT, "data", "sep2060-records.json"),
              "r", encoding="ascii") as fh:
        recs = json.load(fh)
    plain, gist, _raw = build_2060(recs)
    digests = {"plain": rows_sha256(plain), "gist": rows_sha256(gist)}
    del plain, gist
    check("the rebuilt digests reproduce the pins",
          digests["plain"] == SHA_PLAIN and digests["gist"] == SHA_GIST,
          "%s... / %s..." % (digests["plain"][:16], digests["gist"][:16]))

    print("\n[1] the fabricated profiles satisfy every numeric identity")
    for tag in TAGS:
        p = FABRICATED[tag]
        check("%-5s  %d bins, all = %d (mod 8), total == C(2060,4), second "
              "moment == %d" % (tag, len(p), N % 8, second_moment_want(N)),
              all(0 <= k <= N and k % 8 == N % 8 for k in p)
              and all(is_int(v) and v > 0 for v in p.values())
              and sum(p.values()) == c_n_4(N)
              and sum(k * k * v for k, v in p.items())
              == second_moment_want(N))
    check("the two fabricated profiles differ, so a certificate accepting "
          "them on numeric identities alone would call them INEQUIVALENT",
          FABRICATED["plain"] != FABRICATED["gist"])

    print("\n[2] negative controls -- every one of these must be REFUSED")
    cases = []

    b = _bank(digests)
    for p in b:
        del b[p]["schema"]
    cases.append(("N1  no schema field", b, "field-missing"))

    b = _bank(digests)
    for p in b:
        b[p]["schema"] = "sep2060-exact-profile/0"
    cases.append(("N2  wrong schema version", b, "schema"))

    b = _bank(digests)
    for p in b:
        del b[p]["matrix_canonical_sha256"]
    cases.append(("N3  no matrix binding", b, "field-missing"))

    b = _bank(digests)
    for p in b:
        b[p]["matrix_canonical_sha256"] = "0" * 64
    cases.append(("N4  bound to a matrix this script did not rebuild", b,
                  "matrix-binding"))

    b = _bank(digests)
    for p in b:
        b[p]["matrix_canonical_sha256"] = digests[
            "gist" if b[p]["tag"] == "plain" else "plain"]
    cases.append(("N5  plain and gist bindings swapped", b, "matrix-binding"))

    b = _bank(digests)
    for p in sorted(b)[2:]:
        del b[p]
    cases.append(("N6  a PARTIAL set (2 of 4) -- an error, not an absence", b,
                  "partial-set"))

    b = _bank(digests)
    b[os.path.join(ROOT, "data", "sep2060-exact-blas-plain-v2.json")] = \
        _blob("blas", "plain", FABRICATED["plain"], digests["plain"])
    cases.append(("N7  an unknown basename matching the glob", b,
                  "unknown-basename"))

    b = _bank(digests)
    for p in b:
        if b[p]["tag"] == "plain":
            b[p]["profile"]["4"] = -320845991375
    cases.append(("N8  a negative count", b, "profile-count"))

    b = _bank(digests)
    for p in b:
        if b[p]["tag"] == "plain":
            b[p]["profile"]["12"] = 0
    cases.append(("N9  a zero-count bin", b, "profile-count"))

    b = _bank(digests)
    for p in b:
        if b[p]["tag"] == "plain":
            b[p]["profile"]["2068"] = b[p]["profile"].pop("60")
    cases.append(("N10 a bin key outside [0, 2060]", b, "profile-key"))

    b = _bank(digests)
    for p in b:
        if b[p]["tag"] == "plain":
            b[p]["profile"]["61"] = b[p]["profile"].pop("60")
    cases.append(("N11 a bin key not = 4 (mod 8)", b, "profile-key"))

    b = _bank(digests)
    for p in b:
        if b[p]["tag"] == "plain":
            b[p]["profile"]["004"] = b[p]["profile"].pop("4")
    cases.append(("N12 a bin key not in canonical decimal form", b,
                  "profile-key"))

    b = _bank(digests)
    for p in b:
        b[p]["total"] = c_n_4(N) - 1
    cases.append(("N13 a declared total that is not the sum of the bins", b,
                  "profile-total"))

    b = _bank(digests)
    for p in b:
        b[p]["second_moment"] = second_moment_want(N) - 1
    cases.append(("N14 a declared second moment that is not the bins'", b,
                  "profile-second-moment"))

    b = _bank(digests)
    for p in b:
        if b[p]["impl"] == "bits" and b[p]["tag"] == "plain":
            b[p]["profile"] = dict(
                (str(k), v) for k, v in sorted(FABRICATED["gist"].items()))
    cases.append(("N15 blas and bits disagreeing on one matrix", b,
                  "impl-disagreement"))

    b = _bank(digests)
    for p in b:
        b[p]["n"] = 668
    cases.append(("N16 the wrong order", b, "n"))

    b = _bank(digests)
    for p in b:
        b[p]["producer"] = ""
    cases.append(("N17 no named producer", b, "producer"))

    b = _bank(digests)
    for p in b:
        b[p]["tag"] = "plain"
    cases.append(("N18 a tag that contradicts the filename", b, "tag"))

    b = _bank(digests)
    for p in b:
        b[p]["exact"] = True
    cases.append(("N19 an unrecognised field", b, "unknown-field"))

    for label, bank, reason in cases:
        ok, why = _refused(bank, digests, reason)
        check(label, ok, why)

    dup = _bank(digests)
    dpaths = sorted(dup) + [sorted(dup)[0]]
    try:
        accept_bank(dpaths, digests, lambda p: dup[p])
        ok, why = False, "ACCEPTED -- the gate did not close"
    except BankError as e:
        ok, why = e.reason == "duplicate-basename", "refused: %s" % e.reason
    check("N20 the same basename presented twice", ok, why)

    mal = _bank(digests)
    first = sorted(mal)[0]

    def _truncated(p):
        if p == first:                       # a truncated / non-JSON file
            raise ValueError("Expecting value: line 1 column 1 (char 0)")
        return json.loads(json.dumps(mal[p]))

    try:
        accept_bank(sorted(mal), digests, _truncated)
        ok, why = False, "ACCEPTED -- the gate did not close"
    except BankError as e:
        ok, why = e.reason == "malformed-file", "refused: %s" % e.reason
    except Exception as e:                   # the defect this control guards
        ok, why = False, "ESCAPED as %s -- not a BankError" % type(e).__name__
    check("N21 a truncated or non-JSON bank file", ok, why)

    partial = dict((b, "0" * 64) for b in sorted(EXPECTED_BANK)[:3])
    try:
        validate_pin_coverage(partial)
        ok, why = False, "ACCEPTED -- the gate did not close"
    except BankError as e:
        ok, why = e.reason == "pin-coverage", "refused: %s" % e.reason
    check("N22 EXACT_FILE_PINS non-empty but covering only 3 of the 4 files",
          ok, why)

    print("\n[3] the positive control -- the gate must also OPEN")
    good = _bank(digests)
    prof = None
    try:
        prof = accept_bank(sorted(good), digests, lambda p: good[p])
        opened = True
        why = "4 files accepted, %d + %d bins" % (
            len(prof[("plain", "blas")]), len(prof[("gist", "blas")]))
    except BankError as e:
        opened, why = False, "REFUSED: %s -- %s" % (e.reason, e.detail)
    check("P1  a well-formed 4-file bank, bound to the digests rebuilt here, "
          "IS accepted", opened, why)
    check("P1  the accepted bank carries all four (tag, impl) profiles, blas "
          "and bits agreeing",
          bool(prof) and sorted(prof) == sorted((t, i) for t in TAGS
                                                for i in IMPLS))

    print("\n      P1 is the acceptance PREDICATE, not the verdict printer:")
    print("      run_exact is not called and no verdict text is produced.")
    print("      P1 also uses the SAME fabricated counts as the negative")
    print("      controls, correctly bound -- and that is the point.  The")
    print("      acceptance layer checks form and DECLARED identity.  It")
    print("      cannot check that the counts came from the matrix.  A")
    print("      self-declared digest is not proof of computation; the proof")
    print("      of computation is the producer's registered run.")

    print("\n" + "=" * 74)
    if FAIL:
        print("cert 07 --selftest: FAIL (%d): %s" % (len(FAIL), FAIL))
        print("=" * 74)
        return 1
    print("cert 07 --selftest: PASS.  %d negative controls refused for the"
          % (len(cases) + 3))
    print("expected reason; the positive control accepted.  The exact-mode")
    print("gate closes on the fabricated bank AND opens on a well-formed one.")
    print("=" * 74)
    return 0


if __name__ == "__main__":
    sys.exit(main())
