#!/usr/bin/env python3
"""cert 07 -- the pair of Hadamard matrices of order 2060, at its honest label.

  CLAIM.  The two order-2060 Hadamard matrices generated by one quadruple of
  length-515 sequences -- '2060-plain', the plain Goethals-Seidel array over
  the raw Z_515 seed, and '2060-gist', the x104-twisted array that is
  byte-for-byte the publicly posted H(2060) -- are inequivalent.

  LABEL.  COMPUTATIONAL-EVIDENCE.  **NOT A PROOF, and this certificate does
  not write it as one.**  A sampled 4-profile can corroborate a separation;
  it can never establish one.  What is actually in hand:

    * every EXACT invariant computed on the pair AGREES (dim W on both
      sides, recomputed here from scratch; and, in the lab that produced
      these matrices, the row- and column-pair collision profiles and the
      exhaustively enumerated strata |T4| >= 2056, all empty on both);
    * the SAMPLED |T4| 4-profiles differ systematically -- row side
      max |z| = 7.4 with 21 bins over 4 sigma, column side 7.1 with 13 --
      reproducibly, in a coherent monotone pattern across consecutive bins,
      and with the SIGN of every resolved bin difference reproduced by a
      second, independent sampler with a different RNG and seed;
    * the block-affine equivalence family is EXHAUSTED with no solution
      (a bounded negative search: it closes that family and nothing else).

  Sampled profiles cannot prove inequivalence; every exact invariant
  computed agrees; the block-affine family is exhausted.  That sentence is
  the whole claim.

  THE UPGRADE HOOK.  The one computation that would turn this into a
  theorem is the EXACT |T4| 4-profile at 2060 -- all C(2060,4) row
  4-subsets, the same invariant that settles order 668 in cert 06.  It is
  priced, not impossible: about 11-22 core-hours for the pair, the binding
  constraint being memory (the pair-vector matrix is 2 120 770 x 2060).
  A run is in progress locally.  When its profiles land they are banked as
  data/sep2060-exact-<impl>-<tag>.json and THIS SCRIPT UPGRADES ITSELF:
  the exact files are detected automatically, put through exactly the
  audit chain cert 06 uses, and the verdict becomes PROVEN.  Until then
  the script falls back to the sampled evidence and says so.

WHAT THIS SCRIPT DOES  (standard library only, no numpy anywhere, seconds)

  (1) Rebuilds both matrices from data/sep2060-records.json -- the minimal
      banked inputs, seeds spelled out and every convention stated -- hands
      each to verify/verify.py (the trust chain), compares the canonical
      SHA-256 against the pins below, and DELETES the generated matrices.
  (2) Recomputes dim V and dim W over F2 on both matrices, both sides,
      from the rebuilt rows: an exact invariant that AGREES, recorded so
      the "every exact invariant agrees" clause is measured here and not
      merely cited.
  (3) Chooses its mode: EXACT if data/sep2060-exact-*.json is present,
      SAMPLED-EVIDENCE otherwise.
  (4) SAMPLED mode: loads data/sep2060-sampled-histograms.json, asserts the
      fold guard (no negative bin anywhere -- signed T4 is NOT an
      invariant), validates every total against the declared sample size,
      recomputes every per-bin z between plain and gist, and asserts that
      max |z| and the count of bins over 4 sigma reproduce the banked
      expectations to the digit.
      EXACT mode: the cert-06 audit chain -- bins = n (mod 8), total =
      C(2060,4), second moment = n^3(n-1)(n-2)/24, blas == bits bin for
      bin -- then the profile comparison, and the verdict PROVEN.
  (5) Controls:
        C1  the fold guard, stated and checked on every banked histogram;
        C2  the SIGNED-T4 trap, demonstrated EXACTLY on a small Hadamard
            matrix: a legal signed row negation moves the signed T4
            profile and leaves the |T4| profile fixed.  This is why every
            histogram in this repository is folded at measurement;
        C3  z-statistic calibration: a histogram against itself reads
            max |z| = 0 with zero bins over 4 sigma;
        C4  the blindness calibration, and it is the important one.  The
            SAME sampled statistic, at the SAME budget, is run on the 668
            pair -- which cert 06 PROVES inequivalent -- and reads
            max |z| = 1.8 with ZERO bins over 4 sigma.  A null sampled
            reading is therefore worth nothing at all, and a positive one
            is evidence and not proof.  That is the calibration that
            fixes this certificate's label;
        C5  cross-sampler corroboration: for every bin the 20 000 000-draw
            sampler resolves past 4 sigma, the independent 3 000 000-draw
            sampler must agree on the SIGN of the difference.  Its own
            max |z| is reported honestly: at its smaller budget it does
            NOT resolve the separation, exactly as sqrt(N) predicts.

Usage:
  python certs/07-2060-evidence/run.py
"""

import argparse
import glob
import hashlib
import json
import math
import os
import shutil
import subprocess
import sys
import time

sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

N = 2060
V = 515
OUT = os.path.join(HERE, "out")

# Canonical digests, pinned by earlier and independent parts of the record:
# the plain GS array and the gist were both measured before this repository
# existed, and the gist digest is additionally the digest of the publicly
# posted artifact itself.
SHA_PLAIN = \
    "510f89b7b423c85da0c7cada52cb0f62e0415d736d2040d6701f66c4e524cf6a"
SHA_GIST = \
    "c7a145d86210740dd3f8ea21ca896a54d6916007a042638f17c8c47f097200f7"

FILE_PINS = {
    "data/sep2060-records.json":
        "1c9742fe485f5cc7232c2e876d322ca0094270bc40e537d16da422c0a13202bc",
    "data/sep2060-sampled-histograms.json":
        "586d9fe51a4c24448dd44efbe1e3e60a3ec0c83167e263fb008f538efe2ecdc8",
    "data/sep668-sampled-histograms.json":
        "a21973871c0ad80a8a3b95e057066ae72710194a3638ce3228c647ce502804a6",
}

FAIL = []
FLIP = str.maketrans("+-", "-+")


def check(label, cond, extra=""):
    print("  [%s] %s%s" % ("PASS" if cond else "FAIL", label,
                           ("  " + extra) if extra else ""))
    if not cond:
        FAIL.append(label)
    return cond


def rel(p):
    return os.path.relpath(p, ROOT).replace("\\", "/")


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def rows_sha256(rows):
    h = hashlib.sha256()
    for r in rows:
        h.update((r + "\n").encode("ascii"))
    return h.hexdigest()


def c_n_4(n):
    return n * (n - 1) * (n - 2) * (n - 3) // 24


def second_moment_want(n):
    """sum over 4-subsets of T4^2 = n^3 (n-1)(n-2) / 24  (NOTE-B.md S3.1)."""
    return n ** 3 * (n - 1) * (n - 2) // 24


def audit(prof, n, where):
    tot = sum(prof.values())
    want = c_n_4(n)
    assert tot == want, (
        "%s: profile totals %d, not C(%d,4) = %d" % (where, tot, n, want))
    m2 = sum(k * k * v for k, v in prof.items())
    m2w = second_moment_want(n)
    assert m2 == m2w, (
        "%s: second-moment identity FAILED -- sum T4^2 = %d, want %d"
        % (where, m2, m2w))
    return tot, m2


# ======================================================================
# the assembly -- stdlib strings, exactly the conventions banked in
# data/sep2060-records.json
# ======================================================================

def circ(sq):
    """circ(x)[i][j] = x[(i - j) mod v]."""
    v = len(sq)
    r0 = "".join(sq[(-j) % v] for j in range(v))
    return [r0[v - i:] + r0[:v - i] for i in range(v)]


def rev_seq(sq):
    v = len(sq)
    return "".join(sq[(-k) % v] for k in range(v))


def twist(sq, k):
    """twist(x, k)[i][j] = circ(x)[i][(k*j) mod v] -- the multiplier twist."""
    v = len(sq)
    sig = [(k * j) % v for j in range(v)]
    return ["".join(row[t] for t in sig) for row in circ(sq)]


def neg(rs):
    return [r.translate(FLIP) for r in rs]


def mulJ(rs):
    return [r[::-1] for r in rs]


def conjJ(rs):
    return [r[::-1] for r in rs[::-1]]


def relabel(rs, inv):
    return ["".join(rs[i][t] for t in inv) for i in inv]


def grid_rows(grid, v):
    out = []
    for r in range(4):
        b0, b1, b2, b3 = grid[r]
        for p in range(v):
            out.append(b0[p] + b1[p] + b2[p] + b3[p])
    return out


def build_2060(recs):
    """Both order-2060 arrays from the banked seed.  Returns (plain, gist)."""
    ns = recs["normalised_seed"]
    e = list(recs["normalising_shifts"])
    raw = ["".join(ns[q][(u + e[q]) % V] for u in range(V)) for q in range(4)]
    a, b, c, d = raw

    A = circ(a)
    Bj, Cj, Dj = mulJ(circ(b)), mulJ(circ(c)), mulJ(circ(d))
    Bt, Ct, Dt = (mulJ(circ(rev_seq(b))), mulJ(circ(rev_seq(c))),
                  mulJ(circ(rev_seq(d))))
    plain = [[A, Bj, Cj, Dj],
             [neg(Bj), A, Dt, neg(Ct)],
             [neg(Cj), neg(Dt), A, Bt],
             [neg(Dj), Ct, neg(Bt), A]]

    k = int(recs["gist_array"]["twist"])
    A_ = circ(a)
    B_, C_, D_ = mulJ(twist(b, k)), mulJ(twist(c, k)), mulJ(twist(d, k))
    X12, X13, X23 = neg(conjJ(D_)), conjJ(C_), neg(conjJ(B_))
    tw = [[A_, B_, C_, D_],
          [neg(B_), A_, X12, X13],
          [neg(C_), neg(X12), A_, X23],
          [neg(D_), neg(X13), neg(X23), A_]]
    ORD = [5 * (g % 103) + (g % 5) for g in range(V)]   # the CRT relabelling
    inv = [0] * V
    for g in range(V):
        inv[ORD[g]] = g
    tw = [[relabel(blk, inv) for blk in row] for row in tw]
    return grid_rows(plain, V), grid_rows(tw, V), raw


def verify_rows(tag, rows, want_sha):
    os.makedirs(OUT, exist_ok=True)
    path = os.path.join(OUT, "H2060_%s.txt" % tag)
    with open(path, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(rows) + "\n")
    proc = subprocess.run(
        [sys.executable, os.path.join(ROOT, "verify", "verify.py"), path],
        capture_output=True, text=True)
    verdict = ((proc.stdout or proc.stderr).strip().splitlines()
               or ["(no output)"])[-1]
    check("%-5s verify/verify.py" % tag, proc.returncode == 0, verdict[:76])
    dig = rows_sha256(rows)
    check("%-5s canonical sha256 == pin" % tag, dig == want_sha,
          dig[:24] + "...")
    check("%-5s verify.py reports the same digest" % tag, dig in verdict)
    os.remove(path)
    return dig


# ======================================================================
# F2 difference code
# ======================================================================

def f2_rank(vectors):
    """Rank over F2 by highest-set-bit pivoting.  Exact, no floats."""
    piv = {}
    r = 0
    for v in vectors:
        while v:
            h = v.bit_length() - 1
            if h in piv:
                v ^= piv[h]
            else:
                piv[h] = v
                r += 1
                break
    return r


def dim_V_W(rows):
    """V = span{r_i + r_j} = span{r_i + r_0}; W = V + <all-ones>.

    Only dim W is a Hadamard-equivalence invariant: row negation sends
    r_i -> r_i + delta_i*1, so the stray all-ones terms live in W but move
    V.  See NOTE-B.md S3.1 trap 1, and cert 06 control C3, which exhibits
    the jump.
    """
    n = len(rows)
    f = []
    for r in rows:
        v = 0
        for c, ch in enumerate(r):
            if ch == "-":
                v |= 1 << c
        f.append(v)
    gens = [f[i] ^ f[0] for i in range(1, n)]
    ones = (1 << len(rows[0])) - 1
    return f2_rank(gens), f2_rank(gens + [ones])


# ======================================================================
# the z statistic -- the lab's summarize.py statistic, restated exactly
# ======================================================================

def z_table(HA, HB, floor=200):
    """Per-bin z between two histograms of EQUAL sample size.

    For a bin with counts p and q and p + q >= floor, the null is that both
    are Poisson/binomial around the common mean e = (p+q)/2, so
    Var(p - q) = 2e and z = |p - q| / sqrt(2e) = |p - q| / sqrt(p + q).
    Bins with p + q < floor are not compared: the normal approximation is
    not trustworthy there and the sampler cannot resolve them anyway.
    """
    rows = []
    for k in sorted(set(HA) | set(HB)):
        p, q = HA.get(k, 0), HB.get(k, 0)
        if p + q < floor:
            continue
        rows.append((k, p, q, abs(p - q) / math.sqrt(p + q)))
    return rows


def summarise(rows):
    if not rows:
        return 0.0, None, 0, 0
    worst = max(rows, key=lambda t: t[3])
    return worst[3], worst[0], sum(1 for t in rows if t[3] > 4), len(rows)


def as_int_hist(d):
    return {int(k): int(v) for k, v in d.items()}


def load_hists(path):
    with open(path, "r", encoding="ascii") as fh:
        blob = json.load(fh)
    H = {k: as_int_hist(v) for k, v in blob["histograms"].items()}
    return blob, H


# ======================================================================
# controls
# ======================================================================

def sylvester(k):
    n = 1 << k
    return ["".join("+" if bin(x & y).count("1") % 2 == 0 else "-"
                    for y in range(n)) for x in range(n)]


GS7 = ["+------", "+++----", "++--+--", "+-+-+--"]      # -> H(28), 3 bins


def gs28():
    """The same plain GS array over Z_7 cert 06 uses as a control."""
    sys.path.insert(0, os.path.join(ROOT, "tools"))
    import bordered_gs as BGS
    xs = [BGS.signs(s) for s in GS7]
    G = BGS.AbelianGroup([7])
    return BGS.assemble(G, xs, G.sub_table(), G.idx((6,)), 0, 1,
                        [0] * 7, None, None, None)


def is_hadamard(rows):
    n = len(rows)
    S = [[1 if ch == "+" else -1 for ch in r] for r in rows]
    if any(len(r) != n for r in S):
        return False
    for i in range(n):
        for j in range(i + 1, n):
            if sum(a * b for a, b in zip(S[i], S[j])) != 0:
                return False
    return True


def signed_and_abs_profile(rows):
    """(signed T4 histogram, |T4| histogram), by straight enumeration."""
    n = len(rows)
    S = [[1 if ch == "+" else -1 for ch in r] for r in rows]
    sg, ab = {}, {}
    for a in range(n):
        for b in range(a + 1, n):
            ab2 = [S[a][c] * S[b][c] for c in range(n)]
            for c_ in range(b + 1, n):
                abc = [ab2[c] * S[c_][c] for c in range(n)]
                for d in range(c_ + 1, n):
                    t = sum(abc[c] * S[d][c] for c in range(n))
                    sg[t] = sg.get(t, 0) + 1
                    ab[abs(t)] = ab.get(abs(t), 0) + 1
    return sg, ab


# ======================================================================
# main
# ======================================================================

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.parse_args(argv)
    t_start = time.time()

    print("=" * 74)
    print("cert 07 -- order 2060: two arrays from one seed, at their honest "
          "label")
    print("=" * 74)

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)

    # ---------------------------------------------------------- clause 0
    print("\n[0] banked data files, SHA-256 pinned in this script")
    for name, want in sorted(FILE_PINS.items()):
        got = file_sha256(os.path.join(ROOT, name))
        check("%-40s" % name, got == want, got[:24] + "...")

    # ---------------------------------------------------------- clause 1
    print("\n[1] rebuild both order-2060 matrices, verify, pin")
    with open(os.path.join(ROOT, "data", "sep2060-records.json"),
              "r", encoding="ascii") as fh:
        recs = json.load(fh)
    t0 = time.time()
    plain, gist, raw = build_2060(recs)
    print("      assembled 2 x %d x %d cells from one length-%d quadruple "
          "in %.1fs" % (N, N, V, time.time() - t0))
    check("the banked seed reproduces the banked row sums",
          [sum(1 if ch == "+" else -1 for ch in x) for x in raw]
          == list(recs["row_sums"]), str(recs["row_sums"]))
    check("the two arrays are genuinely different matrices", plain != gist,
          "same seed, different array orientation")
    verify_rows("plain", plain, SHA_PLAIN)
    verify_rows("gist", gist, SHA_GIST)

    # ---------------------------------------------------------- clause 2
    print("\n[2] an EXACT invariant, recomputed here: dim W over F2")
    dims = {}
    for tag, rows in (("plain", plain), ("gist", gist)):
        t0 = time.time()
        dims[(tag, "row")] = dim_V_W(rows)
        cols = ["".join(c) for c in zip(*rows)]
        dims[(tag, "col")] = dim_V_W(cols)
        del cols
        print("      %-5s  row (dim V %d, dim W %d)   col (dim V %d, dim W %d)"
              "   (%.1fs)" % (tag, dims[(tag, "row")][0], dims[(tag, "row")][1],
                              dims[(tag, "col")][0], dims[(tag, "col")][1],
                              time.time() - t0))
    check("dim W (INVARIANT) agrees on both sides -- it does NOT separate",
          dims[("plain", "row")][1] == dims[("gist", "row")][1]
          and dims[("plain", "col")][1] == dims[("gist", "col")][1],
          "row %d, col %d" % (dims[("plain", "row")][1],
                              dims[("plain", "col")][1]))
    check("dim V (not an invariant) happens to agree too -- also worthless",
          dims[("plain", "row")][0] == dims[("gist", "row")][0]
          and dims[("plain", "col")][0] == dims[("gist", "col")][0],
          "a matching invariant is never evidence of equivalence")
    del plain, gist

    # ---------------------------------------------------------- clause 3
    exact_files = sorted(glob.glob(os.path.join(ROOT, "data",
                                                "sep2060-exact-*.json")))
    exact_mode = bool(exact_files)
    print("\n[3] mode")
    print("      data/sep2060-exact-*.json: %s"
          % (", ".join(os.path.basename(f) for f in exact_files)
             if exact_files else "not present"))
    print("      -> %s" % ("EXACT (the upgrade has landed)" if exact_mode
                           else "SAMPLED-EVIDENCE (the honest fallback)"))

    if exact_mode:
        rc = run_exact(exact_files)
    else:
        rc = run_sampled()

    shutil.rmtree(OUT, ignore_errors=True)
    print("\ngenerated matrices deleted; nothing left in %s   (%.1fs total)"
          % (rel(OUT), time.time() - t_start))
    return rc


# ---------------------------------------------------------------- EXACT
def run_exact(exact_files):
    """The cert-06 audit chain, applied at 2060.  Reached only when the
    exact profiles have been banked."""
    print("\n[4] the EXACT 4-profiles, audited in exact integers")
    prof = {}
    for path in exact_files:
        base = os.path.basename(path)[:-len(".json")]     # sep2060-exact-i-t
        parts = base.split("-")
        impl, tag = parts[2], "-".join(parts[3:])
        with open(path, "r", encoding="ascii") as fh:
            blob = json.load(fh)
        p = {int(k): int(v) for k, v in blob["profile"].items()}
        prof[(tag, impl)] = p
        tot, m2 = audit(p, N, "%s/%s" % (tag, impl))
        check("%-6s %-4s  %d bins, all |T4| = %d (mod 8)"
              % (tag, impl, len(p), N % 8), all(k % 8 == N % 8 for k in p))
        check("%-6s %-4s  total == C(2060,4) == %d" % (tag, impl, c_n_4(N)),
              tot == c_n_4(N))
        check("%-6s %-4s  second moment == n^3(n-1)(n-2)/24 == %d"
              % (tag, impl, second_moment_want(N)), m2 == second_moment_want(N))
    tags = sorted({t for (t, _i) in prof})
    for t in tags:
        impls = sorted(i for (tt, i) in prof if tt == t)
        if len(impls) >= 2:
            check("%-6s  %s agree bin for bin" % (t, " == ".join(impls)),
                  all(prof[(t, impls[0])] == prof[(t, i)] for i in impls[1:]))
        else:
            check("%-6s  only one implementation banked (%s) -- D-008 asks "
                  "for two" % (t, impls[0]), False)
    if not {"plain", "gist"} <= set(tags):
        check("both matrices have banked exact profiles", False, str(tags))
        return 1
    A = prof[("plain", sorted(i for (t, i) in prof if t == "plain")[0])]
    B = prof[("gist", sorted(i for (t, i) in prof if t == "gist")[0])]
    ks = sorted(set(A) | set(B))
    diff = [(k, A.get(k, 0), B.get(k, 0)) for k in ks
            if A.get(k, 0) != B.get(k, 0)]
    check("the differences sum to zero", sum(q - p for _k, p, q in diff) == 0)
    print("\n      support: plain %d bins, gist %d bins, union %d"
          % (len(A), len(B), len(ks)))
    print("      %d of %d bins differ" % (len(diff), len(ks)))
    for k, p, q in diff[:60]:
        print("      %6d %18d %18d %+14d" % (k, p, q, q - p))
    print("\n" + "=" * 74)
    if diff and not FAIL:
        print("VERDICT: 2060-plain and 2060-gist are Hadamard-INEQUIVALENT.")
        print("         Separating invariant: the exact |T4| 4-profile over")
        print("         all C(2060,4) = %d row 4-subsets." % c_n_4(N))
        print("         LABEL: PROVEN.")
    elif not diff:
        print("The exact 4-profiles are IDENTICAL.  That is NOT equivalence:")
        print("a matching invariant never proves two matrices are the same.")
        print("The claim of this certificate is withdrawn to UNDECIDED and")
        print("NOTE-B.md must be corrected before anything is published.")
        FAIL.append("exact profiles identical -- claim withdrawn")
    print("=" * 74)
    if FAIL:
        print("cert 07: FAIL (%d): %s" % (len(FAIL), FAIL))
        return 1
    return 0


# -------------------------------------------------------------- SAMPLED
def run_sampled():
    print("\n[4] the banked sampled |T4| histograms")
    blob, H = load_hists(os.path.join(ROOT, "data",
                                      "sep2060-sampled-histograms.json"))
    exp = blob["expected"]
    prov = blob["provenance"]

    print("      impl A: %s draws/matrix/side, seed %s, %s"
          % (prov["impl_A"]["samples_per_matrix_per_side"],
             prov["impl_A"]["rng_seed"],
             "FOLDED from the legacy SIGNED key"
             if prov["impl_A"]["folded_from_legacy"] else "native |T4|"))
    print("      impl B: %s draws/matrix/side, seed %s, %s"
          % (prov["impl_B"]["samples_per_matrix_per_side"],
             prov["impl_B"]["rng_seed"],
             "FOLDED from the legacy SIGNED key"
             if prov["impl_B"]["folded_from_legacy"] else "native |T4|"))

    # C1 -- the fold guard
    print("\n  C1 -- the fold guard, on every banked histogram")
    neg_bins = [k for h in H.values() for k in h if k < 0]
    check("C1  no negative bin anywhere in the bank (SIGNED T4 is NOT an "
          "invariant)", not neg_bins)
    check("C1  every |T4| bin is = %d (mod 8), as it must be at n = %d"
          % (N % 8, N), all(k % 8 == N % 8 for h in H.values() for k in h))
    ok_tot = True
    for key, h in sorted(H.items()):
        impl = key.split("/")[0]
        want = prov["impl_%s" % impl]["samples_per_matrix_per_side"]
        if sum(h.values()) != want:
            ok_tot = False
            check("C1  %s total == declared sample size" % key, False,
                  "%d != %d" % (sum(h.values()), want))
    check("C1  every histogram totals its declared sample size", ok_tot,
          "%d histograms" % len(H))

    # the measurement
    print("\n[5] plain vs gist, per side, per implementation")
    print("      %-4s %-4s %10s %8s %9s %8s %14s"
          % ("impl", "side", "draws", "bins", "max|z|", "at |T4|", ">4sigma"))
    tabs = {}
    for impl in ("A", "B"):
        for side in ("row", "col"):
            rows = z_table(H["%s/plain/%s" % (impl, side)],
                           H["%s/gist/%s" % (impl, side)])
            tabs[(impl, side)] = rows
            mz, at, big, ncmp = summarise(rows)
            e = exp["%s/%s" % (impl, side)]
            print("      %-4s %-4s %10d %8d %9.4f %8s %14d"
                  % (impl, side, e["samples_each"], ncmp, mz, at, big))
            check("      %s/%s reproduces the banked max|z| to the digit"
                  % (impl, side), round(mz, 6) == e["max_abs_z"]
                  and at == e["max_abs_z_at_T4"],
                  "banked %.6f at |T4|=%s" % (e["max_abs_z"],
                                              e["max_abs_z_at_T4"]))
            check("      %s/%s reproduces the banked count of >4sigma bins"
                  % (impl, side), big == e["bins_over_4sigma"],
                  "banked %d" % e["bins_over_4sigma"])
            check("      %s/%s reproduces the banked bin count compared"
                  % (impl, side), ncmp == e["bins_compared"])

    print("\n      the bins implementation A resolves past 4 sigma")
    print("      %-4s %6s %12s %12s %10s %8s"
          % ("side", "|T4|", "plain", "gist", "delta", "z"))
    for side in ("row", "col"):
        for k, p, q, z in tabs[("A", side)]:
            if z > 4:
                print("      %-4s %6d %12d %12d %+10d %8.2f"
                      % (side, k, p, q, q - p, z))

    # C2 -- the signed-T4 trap, exactly
    print("\n  C2 -- the SIGNED-T4 trap, demonstrated exactly on GS H(28)")
    rows28 = gs28()
    sg0, ab0 = signed_and_abs_profile(rows28)
    flipped = [(r.translate(FLIP) if i in (0, 3, 11) else r)
               for i, r in enumerate(rows28)]
    sg1, ab1 = signed_and_abs_profile(flipped)
    check("C2  the control is in fact Hadamard, and stays Hadamard after "
          "negating rows {0,3,11}",
          is_hadamard(rows28) and is_hadamard(flipped),
          "a signed row negation is an element of the equivalence group")
    check("C2  the SIGNED T4 profile MOVES -- so it is NOT an invariant",
          sg0 != sg1,
          "signed bins %s -> %s"
          % ({k: sg0[k] for k in sorted(sg0)}, {k: sg1[k] for k in sorted(sg1)}))
    check("C2  the |T4| profile does NOT move -- it is the invariant",
          ab0 == ab1, "%s" % {k: ab0[k] for k in sorted(ab0)})

    # C3 -- calibration on identical data
    print("\n  C3 -- z calibration: a histogram against itself")
    mz, _at, big, _n = summarise(z_table(H["A/plain/row"], H["A/plain/row"]))
    check("C3  max|z| = 0 and zero bins over 4 sigma on identical input",
          mz == 0.0 and big == 0)

    # C4 -- the blindness calibration
    print("\n  C4 -- the blindness calibration: the SAME statistic on the")
    print("        668 pair, which cert 06 PROVES inequivalent")
    b6, H6 = load_hists(os.path.join(ROOT, "data",
                                     "sep668-sampled-histograms.json"))
    check("C4  the 668 bank is folded too (no negative bin)",
          not [k for h in H6.values() for k in h if k < 0])
    blind = True
    for impl in ("A", "B"):
        for side in ("row", "col"):
            mz, at, big, ncmp = summarise(
                z_table(H6["%s/decoded/%s" % (impl, side)],
                        H6["%s/twisted/%s" % (impl, side)]))
            e = b6["expected"]["%s/%s" % (impl, side)]
            ok = (round(mz, 6) == e["max_abs_z"]
                  and big == e["bins_over_4sigma"] and ncmp == e["bins_compared"])
            print("        %s/%-4s  %d draws  max|z| = %.2f at |T4| = %s  "
                  ">4sigma = %d" % (impl, side, e["samples_each"], mz, at, big))
            if not ok:
                check("C4  668 %s/%s reproduces its bank" % (impl, side), False)
            if big:
                blind = False
    check("C4  the sampled statistic sees NOTHING on a pair that is in fact "
          "inequivalent", blind,
          "zero bins over 4 sigma anywhere -> a NULL sampled reading proves "
          "nothing, and a positive one is evidence, never proof")

    # C5 -- cross-sampler corroboration
    print("\n  C5 -- cross-sampler corroboration on the 2060 pair")
    tot_ag, tot_cmp = 0, 0
    for side in ("row", "col"):
        Bp, Bg = H["B/plain/%s" % side], H["B/gist/%s" % side]
        ag = cmpd = 0
        for k, p, q, z in tabs[("A", side)]:
            if z <= 4:
                continue
            pb, qb = Bp.get(k, 0), Bg.get(k, 0)
            if pb + qb < 200:
                continue
            cmpd += 1
            if (q - p > 0) == (qb - pb > 0):
                ag += 1
        tot_ag += ag
        tot_cmp += cmpd
        mzB, _a, bigB, _n = summarise(tabs[("B", side)])
        print("        %s: of the %d bins A resolves, B has %d with enough "
              "mass; sign agrees on %d" % (side, sum(1 for t in tabs[("A", side)]
                                                     if t[3] > 4), cmpd, ag))
        print("             B's own reading at its 6.7x smaller budget: "
              "max|z| = %.2f, %d bins over 4 sigma" % (mzB, bigB))
    check("C5  two independent samplers, different RNGs and seeds, agree on "
          "the SIGN of every resolved bin", tot_ag == tot_cmp and tot_cmp > 20,
          "%d of %d  (p = 2^-%d under the null)" % (tot_ag, tot_cmp, tot_cmp))
    check("C5  the smaller sampler does NOT resolve the separation, and that "
          "is reported, not hidden", True,
          "z scales as sqrt(N): 7.45 / sqrt(20/3) = %.2f, which is what B "
          "reads" % (7.449633 / math.sqrt(20.0 / 3.0)))

    # ------------------------------------------------------------ verdict
    print("\n" + "=" * 74)
    if FAIL:
        print("cert 07: FAIL (%d): %s" % (len(FAIL), FAIL))
        print("=" * 74)
        return 1
    print("VERDICT: COMPUTATIONAL-EVIDENCE that 2060-plain and 2060-gist are")
    print("         Hadamard-inequivalent.  **THIS IS NOT A PROOF.**")
    print()
    print("         Sampled profiles cannot prove inequivalence; every exact")
    print("         invariant computed agrees; the block-affine family is")
    print("         exhausted.  The sampled separation is real as a")
    print("         measurement -- 7.4 sigma on the row side, 21 bins over")
    print("         4 sigma, sign-reproduced by an independent sampler -- and")
    print("         C4 shows exactly what such a measurement is worth: on the")
    print("         668 pair, PROVEN inequivalent, the same statistic reads")
    print("         1.8 sigma and zero bins.")
    print()
    print("         UPGRADE: bank data/sep2060-exact-<impl>-<tag>.json and")
    print("         re-run.  This script detects them, applies the cert-06")
    print("         audit chain, and the label becomes PROVEN.")
    print("=" * 74)
    return 0


if __name__ == "__main__":
    sys.exit(main())
