#!/usr/bin/env python3
"""cert 19 -- the decoded order-668 record is NOT equivalent to its own
transpose, and the eight matrices at 668 are pairwise inequivalent.

  THE OBJECTS.  At order 668: H, the decoded (s,i) = (1,1) bordered
  Goethals-Seidel record (certs 01/06); H', its Lemma-T i = 2 rebuild
  (certs 02/06); H*, the paired Hall switch of the public preprint
  (cert 08); H'', the orientation switch of H -- the twelve off-diagonal
  core blocks negated, border unchanged (cert 13); and the transposes of
  all four.  Three of those transposes are already banked and certified:
  (H')^T and (H*)^T in cert 08, (H'')^T in cert 15.  The fourth, H^T, is
  what this certificate adds.

  THEOREM.  H is NOT Hadamard-equivalent to H^T: their exact |T4|
  4-profiles differ in 49 of the 80 bins H populates.  Consequently the
  EIGHT matrices {H, H', H*, H'', H^T, (H')^T, (H*)^T, (H'')^T} are
  PAIRWISE Hadamard-inequivalent -- all 28 profile comparisons separate --
  so ORDER 668 CARRIES AT LEAST EIGHT HADAMARD EQUIVALENCE CLASSES under
  plain Hadamard equivalence.

  AND WHAT IT DOES NOT CHANGE.  Under the TRANSPOSE-EXTENDED relation
  (A ~~ B iff A ~ B or A ~ B^T) the same eight matrices form EXACTLY
  FOUR classes -- the four of certs 08, 13 and 15, unchanged.  Each pair
  {X, X^T} is one class BY DEFINITION, not by computation; the four
  classes are pairwise separated by the two-refutation rule.  Nothing
  here is new under that relation.  The new statement is H !~ H^T, and
  the count is eight.

  PROOF (finite, exact).  The multiset {|T4(i,j,k,l)|} over all
  C(668,4) = 8 222 179 035 row 4-subsets is a Hadamard-equivalence
  invariant (note/NOTE-B.md S3.1, invariant I5), and the transpose of a
  Hadamard matrix is Hadamard, so profile(X^T) is that same invariant
  computed on that other matrix.  An invariant that differs is a
  separation.  All 28 comparisons differ, in two arithmetics that agree
  bin for bin.  For the transpose-extended count: X ~~ X^T holds by
  definition, so there are at most four classes; and for each of the six
  pairs of classes both refutations (X vs Y and X vs Y^T) are nonzero, so
  there are at least four.  []

  WHY H ~ H^T WAS A REAL QUESTION.  Hadamard equivalence is generated by
  row and column negations and permutations; the transpose is NOT in that
  group, and profile(H^T) is the invariant of a DIFFERENT matrix, not a
  restatement of profile(H).  The bordered Goethals-Seidel family is
  closed under transposition (source-laboratory intel, cited in NOTES.md,
  not ported here and not a claim of this repository), which makes H^T
  another member of the same family and the question "same class or not"
  a genuine one.  It is settled here by computation, not by structure.

WHERE THE PROFILE COMES FROM, AND WHAT A DEFAULT RUN ESTABLISHES

  The new C(668,4) enumeration -- H^T -- was not run inside this
  repository.  It ran at the desk (Hadamard-2060, experiments/inequiv/
  exact_profile_big.py, the unchanged engine of certs 11, 13, 14 and 15;
  numpy, three threads; 2026-09-02) under the pre-registration
  experiments/pr0042/REGISTRATION.md, Amendment 2, FLUSHED before the
  matrix it governs was built.  The matrix itself was built by
  transposing the cert-01 record rebuilt through tools/bordered_gs.py,
  and was put through this repository's verify/verify.py BEFORE the run.
  The output is banked in data/.  The DEFAULT path of this script AUDITS
  fifteen banks; `--full` RECOMPUTES the one new profile here.

WHAT THIS SCRIPT DOES  (default path: standard library only, seconds)

  (0) Pins the SHA-256 of all fifteen banked files it reads.
  (1) Rebuilds H from the banked record (every master-theorem hypothesis
      re-checked), verifies it, pins the cert-01 digest; TRANSPOSES it
      in-process, verifies H^T, pins the new digest; forms H'' as cert 13
      does (twelve off-diagonal core blocks negated, alternate-orientation
      identity checked cell by cell) and transposes it, so the (H'')^T
      bank cert 15 introduced is bound by computation in THIS run too.
      H', H*, (H')^T and (H*)^T are certs 06/08's and are NOT rebuilt
      here; their banks are bound by the digests those certificates pin,
      and every check label says which of the two bindings it is using.
  (2) Control C1 -- the dim-V trap, on the real objects and on a matrix
      small enough to move it by hand.
  (3) Audits sixteen banked exact 4-profiles (eight matrices x two
      arithmetics): every bin = 4 (mod 8), total = C(668,4), second
      moment = n^3(n-1)(n-2)/24 recomputed AND compared against the field
      the bank declares, declared matrix digest against the in-process
      digest where the matrix is rebuilt here and against the earlier
      certificate's pin otherwise, and blas == bits bin for bin.
  (4) The separation table: all 28 pairs, in both arithmetics -- the
      seven involving H^T new here, the other 21 re-affirmed from the
      banks certs 06, 08, 13 and 15 pin.
  (5) The two counts, DERIVED IN CODE from those 28 numbers: the 8x8
      pairwise table is fully separated (eight classes exhibited under
      plain equivalence), and the transpose-extended classes number
      exactly four (at most four by definition, at least four by the
      two-refutation rule).
  (6) Controls: the transposed-profile route on matrices small enough for
      straight enumeration (symmetric Sylvester, where profile(M^T) =
      profile(M) is FORCED; Paley H(20), which is MEASURED); the support
      control; the comparator in the null direction; a total-preserving
      corruption only the second moment can catch.
  (7) --full: recompute the H^T profile at 668 here
      (certs/06-668-separation/full_recompute.py, imported, not copied)
      and compare to both new banks bin for bin.

Usage:
  python certs/19-668-transpose-eight-classes/run.py
  python certs/19-668-transpose-eight-classes/run.py --full --impl blas
  python certs/19-668-transpose-eight-classes/run.py --full
"""

import argparse
import hashlib
import json
import os
import shutil
import subprocess
import sys
import time

sys.dont_write_bytecode = True

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
sys.path.insert(0, os.path.join(ROOT, "tools"))

import bordered_gs as BGS                                    # noqa: E402

N = 668
OUT = os.path.join(HERE, "out")

# ---------------------------------------------------------------- the pins
# Canonical SHA-256 of the matrices (the digest verify/verify.py reports).
# "here" marks the ones rebuilt in clause [1] of THIS run; the rest are
# bound by the digests certs 06 and 08 pin, where they are rebuilt.
SHA = {
    "dec":                                                   # here
        "bdeb5059d77e2703211082627b60441b8c888c928a55cc6f295e011941a387b0",
    "dec-T":                                                 # here, NEW
        "7a25f3f722fa33bf86000b2a61727c223ae2e719118b76dce25e5bde162edb25",
    "or":                                                    # here
        "af1c285cbe2def88427381ab3002a267321b282a9fa78ca37e72830b602953c7",
    "or-T":                                                  # here
        "49f97ecfb6bdc05c16df3f46aa360202ed29a88e0618b7e6bbbe690f958538d9",
    "tw":                                                    # cert 06
        "600849b038e7588d15b64e02794517dd6d95e5d62d505aa7d3d77078392008a3",
    "tw-T":                                                  # cert 08
        "32afde351e1f44aa4236cb3c406fbbcd59c5ab2cc3e02c8380e08680db2d19d7",
    "hall":                                                  # cert 08
        "7f6af1d9e9c80fae52c6f178e298144d209c01f6c103db119e6c12425aa1a722",
    "hall-T":                                                # cert 08
        "565a9ca5a9db739f74215474364202a4d35fd691542b18e8ace8bcbb3c190c65",
}
REBUILT_HERE = ("dec", "dec-T", "or", "or-T")
PINNED_BY = {"tw": "cert 06", "tw-T": "cert 08",
             "hall": "cert 08", "hall-T": "cert 08"}

# SHA-256 of the banked data FILES themselves, so a silently edited bank is
# a hard error rather than a different theorem.  The two decoded-T banks
# produced 2026-09-02 are this certificate's own; the other thirteen are
# certs 06, 08, 13 and 15's, reused verbatim.
FILE_PINS = {
    "data/sep668-decoded-T-exact-blas.json":
        "fb6917010cbd9147312c3908a407bcd86252d22bbf343ae3434f182b71e302f5",
    "data/sep668-decoded-T-exact-bits.json":
        "eff70d552abfe6a85327243a6cbb75d81d36589ab87806c890e5545ea9ef57a5",
    "data/sep668-exact-blas-decoded.json":
        "370fffe6c2f5dc53c09d3b74f8c09dd2bc2a39a1ac2b27fb5167ab4d3559387b",
    "data/sep668-exact-bits-decoded.json":
        "7bace61441f17b5e95fff433bdc5939da212e2b8735e8738d7ed3078fae456b7",
    "data/sep668-exact-blas-twisted.json":
        "8526b3cfa7938a9af334e23f722b1c215ffd1e318c0c713ecc3da1b91f5b3afe",
    "data/sep668-exact-bits-twisted.json":
        "f40bbb8c3906d6fc7374e3e04c2b68eaf29393e50b5662f69eee2426ed3f1e9a",
    "data/sep668-twisted-T-exact.json":
        "38355274ec61d33fcd96e24255e4a7b02874150cd914fdfb928d28cee751fc4a",
    "data/sep668-hall-exact-blas.json":
        "35e716ecb43bb6190d5dd6f4160e0bc2bed4f61a3aacf07a36ff9d190810c154",
    "data/sep668-hall-exact-bits.json":
        "a6f703b499d98995f6446a1aed671284c47e99cfe869f3ce8dc8b5fd9394accb",
    "data/sep668-hall-T-exact-blas.json":
        "151fb5d6e70cf56d6a1c2aa124a597a837bca0ecf5d64958b43a34c05383e0db",
    "data/sep668-hall-T-exact-bits.json":
        "48fdb26f8b1ee5135ed278ec866e204c1ab47df168c043fabff8699c0f4fd8bb",
    "data/sep668-orient-exact-blas.json":
        "5ad283be1baea5c191d39ff3d9219e744ae209ff1df10fea5d152cebbb06c6fd",
    "data/sep668-orient-exact-bits.json":
        "f0eeeb6c89415d09fd8c3f08a13e72666ed0ee36c0066a4d9529e4a88745e726",
    "data/sep668-orient-T-exact-blas.json":
        "536e0c136d16b8271a3c7916529fd57c86f6738a8695c1d691f4fbf98455ec2d",
    "data/sep668-orient-T-exact-bits.json":
        "81fae9e0a4f23116067769bffc80451f2c1d834101f9b65f90a2cccf4aab70cf",
}

# (tag, impl) -> bank file.  data/sep668-twisted-T-exact.json is the one bank
# that carries BOTH implementations in a single file and is loaded
# separately, exactly as certs 08 and 15 load it.
PROFILES = {
    ("dec", "blas"): "data/sep668-exact-blas-decoded.json",
    ("dec", "bits"): "data/sep668-exact-bits-decoded.json",
    ("dec-T", "blas"): "data/sep668-decoded-T-exact-blas.json",
    ("dec-T", "bits"): "data/sep668-decoded-T-exact-bits.json",
    ("tw", "blas"): "data/sep668-exact-blas-twisted.json",
    ("tw", "bits"): "data/sep668-exact-bits-twisted.json",
    ("hall", "blas"): "data/sep668-hall-exact-blas.json",
    ("hall", "bits"): "data/sep668-hall-exact-bits.json",
    ("hall-T", "blas"): "data/sep668-hall-T-exact-blas.json",
    ("hall-T", "bits"): "data/sep668-hall-T-exact-bits.json",
    ("or", "blas"): "data/sep668-orient-exact-blas.json",
    ("or", "bits"): "data/sep668-orient-exact-bits.json",
    ("or-T", "blas"): "data/sep668-orient-T-exact-blas.json",
    ("or-T", "bits"): "data/sep668-orient-T-exact-bits.json",
}
TWISTED_T = "data/sep668-twisted-T-exact.json"

LABEL = {"dec": "H", "dec-T": "H^T", "tw": "H'", "tw-T": "(H')^T",
         "hall": "H*", "hall-T": "(H*)^T", "or": "H''", "or-T": "(H'')^T"}

# The four classes of certs 08/13/15 and the transpose of each.  The eight
# tags in table order.
CLASSES = ("dec", "tw", "hall", "or")
TRANSPOSE_OF = {"dec": "dec-T", "tw": "tw-T", "hall": "hall-T", "or": "or-T"}
TAGS = ("dec", "tw", "hall", "or", "dec-T", "tw-T", "hall-T", "or-T")

# Populated-bin counts, pinned so a drifting bank cannot quietly turn this
# certificate into a different statement: 80 for each original, 79 for each
# transpose.
NBINS = {False: 80, True: 79}

# The one bin every transpose leaves empty (a support fact, checked in C3),
# and the extreme bin that survives on all eight (the preprint's Lemma-3
# quadruple; MEASURED, not forced).
DROPPED_BIN = 644
LEMMA3_BIN = 660

# Every one of the 28 pairs, with its differing-bin count, the size of the
# union of the two supports, and where the number comes from.  NEW = needs
# the H^T profile banked 2026-09-02 and is stated for the first time here;
# "cert NN" = the count that certificate states, re-affirmed here from the
# same bank; "banks NN" = computed here from banks that certificate pins,
# not previously stated as a count.
SEP = {
    ("dec", "tw"): (26, 80, "cert 06"),
    ("dec", "hall"): (27, 80, "cert 08"),
    ("dec", "or"): (27, 80, "cert 13"),
    ("dec", "tw-T"): (50, 80, "cert 08"),
    ("dec", "hall-T"): (49, 80, "cert 08"),
    ("dec", "or-T"): (50, 80, "cert 15"),
    ("tw", "hall"): (27, 80, "cert 08"),
    ("tw", "or"): (27, 80, "cert 13"),
    ("tw", "tw-T"): (50, 80, "banks 06/08"),
    ("tw", "hall-T"): (50, 80, "cert 08"),
    ("tw", "or-T"): (50, 80, "cert 15"),
    ("hall", "or"): (26, 80, "cert 13"),
    ("hall", "tw-T"): (49, 80, "cert 08"),
    ("hall", "hall-T"): (50, 80, "banks 08"),
    ("hall", "or-T"): (49, 80, "cert 15"),
    ("or", "tw-T"): (50, 80, "banks 08/13"),
    ("or", "hall-T"): (50, 80, "banks 08/13"),
    ("or", "or-T"): (50, 80, "cert 15"),
    ("tw-T", "hall-T"): (26, 79, "banks 08"),
    ("tw-T", "or-T"): (24, 79, "cert 15"),
    ("hall-T", "or-T"): (25, 79, "cert 15"),
    # ---- the seven the new H^T profile decides ------------------------
    ("dec", "dec-T"): (49, 80, "NEW"),
    ("dec-T", "tw"): (50, 80, "NEW"),
    ("dec-T", "hall"): (50, 80, "NEW"),
    ("dec-T", "or"): (50, 80, "NEW"),
    ("dec-T", "tw-T"): (25, 79, "NEW"),
    ("dec-T", "hall-T"): (24, 79, "NEW"),
    ("dec-T", "or-T"): (26, 79, "NEW"),
}

HEXDIGITS = set("0123456789abcdef")
FLIP = str.maketrans("+-", "-+")
FAIL = []
NCHECK = [0]


def is_sha256(v):
    return (isinstance(v, str) and len(v) == 64
            and all(c in HEXDIGITS for c in v))


def check(label, cond, extra=""):
    NCHECK[0] += 1
    print("  [%s] %s%s" % ("PASS" if cond else "FAIL", label,
                           ("  " + extra) if extra else ""))
    if not cond:
        FAIL.append(label)
    return cond


def rel(p):
    return os.path.relpath(p, ROOT).replace("\\", "/")


def file_sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def rows_sha256(rows):
    """The canonical digest verify.py reports: '+/-' rows, newline-joined."""
    h = hashlib.sha256()
    for r in rows:
        h.update((r + "\n").encode("ascii"))
    return h.hexdigest()


def pair(a, b):
    """SEP is keyed by the pair as written above, in either order."""
    return (a, b) if (a, b) in SEP else (b, a)


# ======================================================================
# exact-integer profile arithmetic
# ======================================================================

def c_n_4(n):
    return n * (n - 1) * (n - 2) * (n - 3) // 24


def second_moment_want(n):
    """sum over 4-subsets of T4^2 = n^3 (n-1)(n-2) / 24  (NOTE-B.md S3.1)."""
    return n ** 3 * (n - 1) * (n - 2) // 24


def audit(prof, n, where):
    """The two forced identities, as ASSERTS.  Exact integers throughout."""
    tot = sum(prof.values())
    want = c_n_4(n)
    assert tot == want, (
        "%s: profile totals %d, not C(%d,4) = %d" % (where, tot, n, want))
    m2 = sum(k * k * v for k, v in prof.items())
    m2w = second_moment_want(n)
    assert m2 == m2w, (
        "%s: second-moment identity FAILED -- sum T4^2 = %d, want "
        "n^3(n-1)(n-2)/24 = %d" % (where, m2, m2w))
    return tot, m2


def compare(pa, pb):
    """(differing bins, delta sum, first-moment delta, union support size)."""
    ks = sorted(set(pa) | set(pb))
    diff = [(k, pa.get(k, 0), pb.get(k, 0)) for k in ks
            if pa.get(k, 0) != pb.get(k, 0)]
    return (diff,
            sum(q - p for _k, p, q in diff),
            sum(k * (q - p) for k, p, q in diff),
            len(ks))


# ======================================================================
# clause 1 -- rebuild, transpose, switch, verify, pin
# ======================================================================

def load_record(path, order):
    with open(path, "r", encoding="ascii") as fh:
        blob = json.load(fh)
    if "orders" in blob:
        return [r for r in blob["orders"] if int(r["order"]) == order][0]
    return blob


def transpose_rows(rows):
    return ["".join(col) for col in zip(*rows)]


def verify_rows(tag, rows):
    """Hand a matrix to the trust chain and pin its canonical digest."""
    path = os.path.join(OUT, "H%d_%s.txt" % (N, tag))
    with open(path, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(rows) + "\n")
    proc = subprocess.run(
        [sys.executable, os.path.join(ROOT, "verify", "verify.py"), path],
        capture_output=True, text=True)
    verdict = ((proc.stdout or proc.stderr).strip().splitlines()
               or ["(no output)"])[-1]
    lab = "%-7s" % LABEL[tag]
    check("%s verify/verify.py" % lab, proc.returncode == 0, verdict[:70])
    dig = rows_sha256(rows)
    check("%s canonical sha256 == pin" % lab, dig == SHA[tag],
          dig[:24] + "...")
    check("%s verify.py reports the same digest" % lab, dig in verdict)
    os.remove(path)
    return dig


def build_and_verify(tag, rec):
    t0 = time.time()
    rep, rows = BGS.check_record(rec)
    lab = "%-7s" % LABEL[tag]
    if not rows:
        check("%s hypotheses" % lab, False, str(rep.get("failures")))
        return rep, None, None
    check("%s hypotheses H0-H4, D1/D3/D5, Sigma-bar, compression lemma"
          % lab, rep["hypotheses_ok"] and rep["compression_lemma_crosscheck"],
          "s=%d i=%d w=%d" % (rep["s"], rep["i"], rep["w"]))
    dig = verify_rows(tag, rows)
    print("       rebuilt and verified in %.1fs" % (time.time() - t0))
    return rep, rows, dig


def transpose_and_verify(tag, rows):
    """Form X^T in-process, check that transposition is a genuine move and
    an involution, put it through the trust chain, pin its digest."""
    ttag = TRANSPOSE_OF[tag]
    rt = transpose_rows(rows)
    lab = "%-7s" % LABEL[ttag]
    check("%s is NOT the original -- the transpose is a different matrix "
          "here" % lab, rt != rows,
          "%d of %d rows differ"
          % (sum(1 for a, b in zip(rt, rows) if a != b), N))
    check("%s transposing twice returns the original, cell for cell" % lab,
          transpose_rows(rt) == rows)
    return rt, verify_rows(ttag, rt)


def orientation_switch(rows, n, s):
    """H'' = H with the twelve off-diagonal core blocks negated.

    Layout (tools/bordered_gs.py): the first 4s rows and columns are the
    border (corner E, row strips); the core follows as four superblocks of n
    rows each, superblock I = (k - 4s) // n.  Border rows/columns untouched.
    """
    b = 4 * s
    Nn = len(rows)
    assert Nn == b + 4 * n

    def blk(k):
        return -1 if k < b else (k - b) // n

    out = []
    for r, row in enumerate(rows):
        I = blk(r)
        if I < 0:
            out.append(row)
            continue
        chars = list(row)
        for c in range(b, Nn):
            if blk(c) != I:
                chars[c] = "+" if chars[c] == "-" else "-"
        out.append("".join(chars))
    return out


def alternate_orientation_identity(rows_H, rows_Hpp, n, s):
    """S H'' S == H_alt, where H_alt negates the six transposed core blocks
    of the standard array (blocks (I,J) with I,J >= 1, I != J), and signs
    the border strips by superblock: P[a][J](-1)^[J != 0], Q[I](-1)^[I != 0].
    A sign-pattern identity, checked cell by cell."""
    b = 4 * s
    Nn = len(rows_H)

    def blk(k):
        return -1 if k < b else (k - b) // n

    def alt_sign(r, c):
        I, J = blk(r), blk(c)
        if I >= 1 and J >= 1 and I != J:
            return -1
        if I == -1 and J >= 1:
            return -1
        if J == -1 and I >= 1:
            return -1
        return 1

    sg = [1 if blk(k) <= 0 else -1 for k in range(Nn)]
    for r in range(Nn):
        hr, pr = rows_H[r], rows_Hpp[r]
        for c in range(Nn):
            lhs = sg[r] * sg[c] * (1 if pr[c] == "+" else -1)
            rhs = alt_sign(r, c) * (1 if hr[c] == "+" else -1)
            if lhs != rhs:
                return False
    return True


# ======================================================================
# F2 difference code -- dim V (NOT invariant) and dim W (invariant)
# ======================================================================

def f2_rows(rows):
    """'+' -> 0, '-' -> 1, one Python int per row (bit c = column c)."""
    out = []
    for r in rows:
        v = 0
        for c, ch in enumerate(r):
            if ch == "-":
                v |= 1 << c
        out.append(v)
    return out


def f2_rank(vectors):
    basis = []
    for v in vectors:
        for b in basis:
            v = min(v, v ^ b)
        if v:
            basis.append(v)
            basis.sort(reverse=True)
    return len(basis)


def dim_V_W(rows):
    """V = span{r_i + r_j}, W = V + <all-ones>."""
    f = f2_rows(rows)
    n = len(rows)
    gens = [f[i] ^ f[0] for i in range(1, n)]
    ones = (1 << len(rows[0])) - 1
    return f2_rank(gens), f2_rank(gens + [ones])


# ======================================================================
# small-matrix controls
# ======================================================================

def sylvester(k):
    n = 1 << k
    return ["".join("+" if bin(x & y).count("1") % 2 == 0 else "-"
                    for y in range(n)) for x in range(n)]


def sylvester_profile_forced(n):
    hit = n * (n - 1) * (n - 2) // 24
    return {0: c_n_4(n) - hit, n: hit}


def paley1(q):
    """Paley type I Hadamard matrix of order q+1, q prime = 3 (mod 4)."""
    res = {(x * x) % q for x in range(1, q)}

    def chi(a):
        a %= q
        return 0 if a == 0 else (1 if a in res else -1)

    n = q + 1
    M = [[0] * n for _ in range(n)]
    M[0][0] = 1
    for j in range(1, n):
        M[0][j] = 1
        M[j][0] = -1
    for i in range(1, n):
        for j in range(1, n):
            M[i][j] = 1 if i == j else chi(i - j)
    return ["".join("+" if v == 1 else "-" for v in row) for row in M]


def is_hadamard(rows):
    n = len(rows)
    S = [[1 if ch == "+" else -1 for ch in r] for r in rows]
    if any(len(r) != n for r in S):
        return False
    for i in range(n):
        for j in range(i + 1, n):
            if sum(a * b for a, b in zip(S[i], S[j])) != 0:
                return False
    return True


def profile_straight(rows):
    """Straight O(C(n,4)) enumeration over the +-1 entries."""
    n = len(rows)
    S = [[1 if ch == "+" else -1 for ch in r] for r in rows]
    hist = {}
    for a in range(n):
        Sa = S[a]
        for b in range(a + 1, n):
            Sb = S[b]
            ab = [Sa[c] * Sb[c] for c in range(n)]
            for c_ in range(b + 1, n):
                Sc = S[c_]
                abc = [ab[c] * Sc[c] for c in range(n)]
                for d in range(c_ + 1, n):
                    Sd = S[d]
                    t = 0
                    for c in range(n):
                        t += abc[c] * Sd[c]
                    t = abs(t)
                    hist[t] = hist.get(t, 0) + 1
    return {k: v for k, v in hist.items() if v}


# ======================================================================
# main
# ======================================================================

def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--full", action="store_true",
                    help="RECOMPUTE the H^T exact profile at 668 here with "
                         "numpy and compare to both new banks bin for bin; "
                         "without it the banked profiles are audited, not "
                         "recomputed")
    ap.add_argument("--impl", choices=("blas", "bits", "both"),
                    default="both",
                    help="which arithmetic path --full recomputes")
    args = ap.parse_args(argv)
    t_start = time.time()

    print("=" * 72)
    print("cert 19 -- order 668: H is NOT equivalent to H^T, and the EIGHT")
    print("           matrices are pairwise inequivalent (still four classes")
    print("           with the transpose in the group)")
    print("=" * 72)

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)
    os.makedirs(OUT)
    try:
        rc = _body(args, t_start)
    finally:
        shutil.rmtree(OUT, ignore_errors=True)
    print("generated matrices deleted; nothing left in %s   (%.1fs)"
          % (rel(OUT), time.time() - t_start))
    return rc


def _body(args, t_start):
    # ---------------------------------------------------------- clause 0
    print("\n[0] the fifteen banked data files, SHA-256 pinned in this script")
    for name, want in sorted(FILE_PINS.items()):
        got = file_sha256(os.path.join(ROOT, name))
        check("%-42s" % name, got == want, got[:24] + "...")

    # ---------------------------------------------------------- clause 1
    print("\n[1] rebuild H, transpose it, form H'' and transpose that; "
          "verify and pin all four")
    print("    H', H*, (H')^T and (H*)^T are certs 06/08's and are NOT "
          "rebuilt here -- their")
    print("    banks are bound by the digests those certificates pin.")
    dec_rec = load_record(os.path.join(ROOT, "data", "payload-records.json"),
                          N)
    rep_d, rows_d, dig_d = build_and_verify("dec", dec_rec)
    if rows_d is None:
        print("\nFATAL: the decoded matrix did not rebuild.")
        return 1
    n, s = int(rep_d["w"]) * int(rep_d["i"]), int(rep_d["s"])
    check("layout n = |G| = %d, s = %d, N = 4(n+s) = %d" % (n, s, 4 * (n + s)),
          4 * (n + s) == N and len(rows_d) == N)

    rows_dT, dig_dT = transpose_and_verify("dec", rows_d)

    rows_o = orientation_switch(rows_d, n, s)
    check("H''     differs from H in exactly the twelve off-diagonal core "
          "blocks",
          sum(1 for r in range(N) for c in range(N)
              if rows_o[r][c] != rows_d[r][c]) == 12 * n * n,
          "%d cells" % (12 * n * n))
    check("H''     S H'' S == the alternate-orientation array with the "
          "signed border",
          alternate_orientation_identity(rows_d, rows_o, n, s))
    dig_o = verify_rows("or", rows_o)
    rows_oT, dig_oT = transpose_and_verify("or", rows_o)

    built = {"dec": dig_d, "dec-T": dig_dT, "or": dig_o, "or-T": dig_oT}
    for tag in PINNED_BY:
        built[tag] = SHA[tag]
    check("the eight matrices are eight DIFFERENT matrices before any "
          "profile is opened", len({built[t] for t in TAGS}) == 8,
          "eight distinct canonical digests")

    # --------------------------------------------------------- clause 2
    print("\n[2] control C1 -- the dim-V trap")
    mats = {"dec": rows_d, "dec-T": rows_dT, "or": rows_o, "or-T": rows_oT}
    dims = {t: dim_V_W(r) for t, r in mats.items()}
    check("C1  dim W (INVARIANT) is 667 on all four objects rebuilt here",
          {v[1] for v in dims.values()} == {667},
          "matching invariants prove nothing: this one separates none of "
          "the six pairs among them")
    check("C1  dim V (NOT invariant) also reads 666 on all four -- and that "
          "agreement is worth nothing",
          {v[0] for v in dims.values()} == {666},
          ", ".join("%s %d" % (LABEL[t], dims[t][0]) for t in TAGS
                    if t in dims) + "  <- do NOT read this as anything")
    for k in (2, 4, 6):
        syl = sylvester(k)
        moved = [syl[0].translate(FLIP)] + syl[1:]
        v0, w0 = dim_V_W(syl)
        v1, w1 = dim_V_W(moved)
        check("C1  Sylvester H(%d): negating one row moves dim V %d -> %d "
              "while dim W stays %d -- Trap 1, demonstrated"
              % (1 << k, v0, v1, w0), v0 != v1 and w0 == w1
              and is_hadamard(moved))

    ROWS = {"dec-T": rows_dT} if args.full else {}
    del rows_d, rows_dT, rows_o, rows_oT, mats

    # ---------------------------------------------------------- clause 3
    print("\n[3] the sixteen banked exact 4-profiles, AUDITED in exact "
          "integers")
    print("    (audited, not recomputed: see --full)")
    prof = {}
    for (tag, impl), name in sorted(PROFILES.items()):
        with open(os.path.join(ROOT, name), "r", encoding="ascii") as fh:
            blob = json.load(fh)
        p = {int(k): int(v) for k, v in blob["profile"].items()}
        prof[(tag, impl)] = p
        _audit_bank(tag, impl, p, blob, built)

    # The twisted-transpose bank carries BOTH implementations in one file.
    with open(os.path.join(ROOT, TWISTED_T), "r", encoding="ascii") as fh:
        tt = json.load(fh)
    check("(H')^T  bank's canonical_sha256 == the digest cert 08 pins",
          tt["canonical_sha256"] == SHA["tw-T"])
    check("(H')^T  bank names the SOURCE matrix cert 06 pins",
          tt.get("source_matrix_canonical_sha256", SHA["tw"]) == SHA["tw"])
    for impl, blk in sorted(tt["implementations"].items()):
        p = {int(k): int(v) for k, v in blk["profile"].items()}
        prof[("tw-T", impl)] = p
        _audit_bank("tw-T", impl, p, blk, built, name_field="matrix_sha256")

    for tag in TAGS:
        a, b = prof[(tag, "blas")], prof[(tag, "bits")]
        check("%-7s blas == bits, bin for bin (two independent "
              "implementations)" % LABEL[tag], a == b, "%d bins" % len(a))
        want = NBINS[tag.endswith("-T")]
        check("%-7s populates %d bins, all |T4| = 4 (mod 8)"
              % (LABEL[tag], want),
              len(a) == want and all(k % 8 == 4 for k in a))

    # ---------------------------------------------------------- clause 4
    print("\n[4] the separation table -- all %d pairs, in both arithmetics"
          % len(SEP))
    keys = sorted(SEP, key=lambda k: (SEP[k][2] == "NEW", k[0], k[1]))
    print("      %-22s %10s %9s %14s  %s"
          % ("pair", "differing", "union", "sum |T4|*delta", "source"))
    for (a, b) in keys:
        want, wantu, src = SEP[(a, b)]
        diff, dsum, m1, u = compare(prof[(a, "blas")], prof[(b, "blas")])
        dbits = compare(prof[(a, "bits")], prof[(b, "bits")])[0]
        print("      %-22s %10d %9d %14d  %s"
              % ("%s vs %s" % (LABEL[a], LABEL[b]), len(diff), u, m1, src))
        check("%-7s vs %-7s  differ in exactly %d of %d bins, deltas "
              "summing to zero, blas and bits alike"
              % (LABEL[a], LABEL[b], want, wantu),
              len(diff) == want and u == wantu and dsum == 0
              and len(dbits) == want, "%d differing" % len(diff))

    print("\n      the new leg the theorem rests on: H vs H^T "
          "(first six divergent bins)")
    diff = compare(prof[("dec", "blas")], prof[("dec-T", "blas")])[0]
    big = max(diff, key=lambda t: abs(t[2] - t[1]))
    print("      largest |delta| = %d at |T4| = %d (%.2e of that bin)"
          % (abs(big[2] - big[1]), big[0],
             abs(big[2] - big[1]) / big[1]))
    for k, p, q in diff[:6]:
        print("        |T4|=%4d  H %16d   H^T %16d   delta %+d"
              % (k, p, q, q - p))
    check("H vs H^T  the FIRST moment, which nothing forces, differs",
          compare(prof[("dec", "blas")], prof[("dec-T", "blas")])[2] != 0,
          "sum |T4|*delta = %d"
          % compare(prof[("dec", "blas")], prof[("dec-T", "blas")])[2])

    # ---------------------------------------------------------- clause 5
    def ndiff(x, y, impl="blas"):
        return len(compare(prof[(x, impl)], prof[(y, impl)])[0])

    print("\n[5] the two counts, DERIVED HERE from those %d numbers"
          % len(SEP))
    print("\n    (a) PLAIN Hadamard equivalence: the 8x8 table of differing "
          "bins")
    print("        %-8s %s" % ("", " ".join("%8s" % LABEL[t] for t in TAGS)))
    table = {}
    for a in TAGS:
        row = []
        for b in TAGS:
            d = 0 if a == b else ndiff(a, b)
            table[(a, b)] = d
            row.append("%8d" % d)
        print("        %-8s %s" % (LABEL[a], " ".join(row)))
    offdiag = [(a, b) for i, a in enumerate(TAGS) for b in TAGS[i + 1:]]
    worst = min(table[(a, b)] for a, b in offdiag)
    check("all %d off-diagonal entries are nonzero, so the EIGHT matrices "
          "are PAIRWISE Hadamard-inequivalent (least separated pair: %d "
          "bins)" % (len(offdiag), worst),
          all(table[(a, b)] > 0 for a, b in offdiag) and worst > 0,
          "eight classes exhibited at 668 under plain equivalence")
    check("the diagonal is zero: every profile against itself, 0 differing "
          "bins", all(table[(t, t)] == 0 for t in TAGS))
    check("the table is symmetric, as a comparison of multisets must be",
          all(table[(a, b)] == table[(b, a)] for a in TAGS for b in TAGS))
    check("the same table in the OTHER arithmetic, entry for entry",
          all(ndiff(a, b, "bits") == table[(a, b)] for a, b in offdiag))

    print("\n    (b) the TRANSPOSE-EXTENDED relation: A ~~ B iff A ~ B or")
    print("        A ~ B^T.  X ~~ X^T holds BY DEFINITION -- no computation")
    print("        -- so the eight collapse to AT MOST the four pairs")
    print("        {X, X^T}.  Each pair of classes then needs TWO")
    print("        refutations; all four routes are available here because")
    print("        all four transposes are banked, and all four must hold.")
    print("\n      %-16s %8s %10s %10s %12s %10s"
          % ("classes", "A vs B", "A vs B^T", "A^T vs B", "A^T vs B^T",
             "verdict"))
    verdicts = {}
    for i, a in enumerate(CLASSES):
        for b in CLASSES[i + 1:]:
            aT, bT = TRANSPOSE_OF[a], TRANSPOSE_OF[b]
            d = (ndiff(a, b), ndiff(a, bT), ndiff(aT, b), ndiff(aT, bT))
            ok = d[0] > 0 and d[1] > 0
            verdicts[(a, b)] = ok
            print("      %-16s %8d %10d %10d %12d %10s"
                  % ("%s vs %s" % (LABEL[a], LABEL[b]), d[0], d[1], d[2],
                     d[3], "SEPARATED" if ok else "OPEN"))
            check("%-4s ~~ %-4s is REFUTED: %d bins against B and %d against "
                  "B^T" % (LABEL[a], LABEL[b], d[0], d[1]), ok)
            check("%-4s vs %-4s  the redundant routes separate too (%d and "
                  "%d bins)" % (LABEL[a], LABEL[b], d[2], d[3]),
                  d[2] > 0 and d[3] > 0)
    check("all %d pairs of the %d transpose-extended classes are separated, "
          "and each class holds exactly two of the eight matrices -- so "
          "there are EXACTLY %d classes among them, the count of certs "
          "08/13/15, UNCHANGED"
          % (len(CLASSES) * (len(CLASSES) - 1) // 2, len(CLASSES),
             len(CLASSES)),
          all(verdicts.values())
          and sorted(TAGS) == sorted([t for c in CLASSES
                                      for t in (c, TRANSPOSE_OF[c])]))
    twelve = []
    for i, a in enumerate(CLASSES):
        for b in CLASSES[i + 1:]:
            twelve.append(pair(a, b))
            twelve.append(pair(a, TRANSPOSE_OF[b]))
    check("nothing here is new under that relation: the %d refutations the "
          "four classes rest on are all certs 06/08/13/15's, and not one of "
          "them needs the new profile" % len(twelve),
          len(twelve) == 12
          and all(SEP[k][2] != "NEW" for k in twelve),
          "sources: " + ", ".join(sorted({SEP[k][2] for k in twelve})))

    # ---------------------------------------------------------- clause 6
    print("\n[6] controls")

    print("\n  C2 -- the transposed-profile route, on matrices small enough")
    print("        for straight O(C(n,4)) enumeration")
    for rows, name in ((sylvester(3), "Sylvester H(8)"),
                       (sylvester(4), "Sylvester H(16)"),
                       (paley1(19), "Paley I H(20)")):
        nn = len(rows)
        rt = transpose_rows(rows)
        p1 = profile_straight(rows)
        p2 = profile_straight(rt)
        audit(p1, nn, name)
        audit(p2, nn, name + "^T")
        check("C2  %-16s the transpose is Hadamard; profile(M^T) audited"
              % name, is_hadamard(rt))
        if rows == rt:
            check("C2  %-16s is SYMMETRIC, so profile(M^T) == profile(M) is "
                  "FORCED -- and holds" % name, p1 == p2, "%d bins" % len(p1))
            check("C2  %-16s matches the forced Sylvester profile" % name,
                  p1 == sylvester_profile_forced(nn))
        else:
            print("      [MEAS] C2  %-16s is not symmetric; profile(M^T) == "
                  "profile(M) is %s (measured, never asserted)"
                  % (name, p1 == p2))
    print("      (C2 exists because the whole certificate rests on")
    print("       transposed profiles.  At 668 the route is not vacuous:")
    print("       every transpose banked here populates one bin FEWER than")
    print("       its original -- H^T included.)")

    print("\n  C3 -- the transposes are genuinely different objects")
    common = set(prof[("dec", "blas")])
    for t in CLASSES[1:]:
        common &= set(prof[(t, "blas")])
    check("C3  the four originals populate the same %d bins, and |T4| = %d "
          "is one of them, with count 1 in each"
          % (NBINS[False], DROPPED_BIN),
          len(common) == NBINS[False]
          and all(prof[(t, "blas")].get(DROPPED_BIN) == 1 for t in CLASSES))
    for t in CLASSES:
        tT = TRANSPOSE_OF[t]
        gone = sorted(common - set(prof[(tT, "blas")]))
        check("C3  %-7s populates %d bins, not %d -- and the bin it loses "
              "is |T4| = %d" % (LABEL[tT], NBINS[True], NBINS[False],
                                DROPPED_BIN),
              gone == [DROPPED_BIN]
              and len(prof[(tT, "blas")]) == NBINS[True]
              and not (set(prof[(tT, "blas")]) - common),
              "missing: %s" % gone)
    print("      [MEAS] C3  |T4| = %d has count 1 on all EIGHT matrices "
          "(the preprint's" % LEMMA3_BIN)
    print("             Lemma-3 quadruple survives transposition): %s -- "
          "measured, not forced"
          % all(prof[(t, "blas")].get(LEMMA3_BIN) == 1 for t in TAGS))

    print("\n  C4 -- the comparator, exercised in the null direction")
    check("C4  every banked profile against itself: 0 differing bins",
          all(compare(prof[(t, i)], prof[(t, i)])[0] == []
              for t in TAGS for i in ("blas", "bits")),
          "%d profiles" % (2 * len(TAGS)))

    print("\n  C5 -- negative control: the second-moment assert must FIRE")
    victim = dict(prof[("dec-T", "blas")])
    kk = sorted(victim)
    victim[kk[0]] -= 1
    victim[kk[-1]] += 1                     # total preserved, m2 moved
    fired = False
    try:
        audit(victim, N, "C5-corrupted")
    except AssertionError as exc:
        fired = "second-moment identity FAILED" in str(exc)
    check("C5  a total-preserving corruption of the new H^T bank is "
          "rejected by audit()", fired,
          "moved one count from |T4|=%d to |T4|=%d" % (kk[0], kk[-1]))
    check("C5  the corrupted profile still totals C(668,4) -- so ONLY the "
          "second moment could catch it", sum(victim.values()) == c_n_4(N))

    # ---------------------------------------------------------- clause 7
    replayed = []
    if args.full:
        impls = (("blas", "bits") if args.impl == "both" else (args.impl,))
        print("\n[7] --full: RECOMPUTING the H^T exact profile at 668 here, "
              "from the rows")
        print("    clause [1] verified, with numpy (%s).  This is the one "
              "new leg." % " and ".join(impls))
        for var in ("OMP_NUM_THREADS", "OPENBLAS_NUM_THREADS",
                    "MKL_NUM_THREADS", "NUMEXPR_NUM_THREADS",
                    "VECLIB_MAXIMUM_THREADS"):
            os.environ[var] = "3"           # set BEFORE numpy is imported
        sys.path.insert(0, os.path.join(ROOT, "certs", "06-668-separation"))
        import full_recompute as FR                          # noqa: E402
        h128 = sylvester(7)
        want128 = sylvester_profile_forced(128)
        for impl in impls:
            got = FR.profile(h128, 128, impl, progress=False)
            audit(got, 128, "full/H128/%s" % impl)
            check("[full] Sylvester H(128) %-4s == the forced profile" % impl,
                  got == want128)
        rows = ROWS["dec-T"]
        check("[full] the rows about to be enumerated are the ones verify.py "
              "accepted", rows_sha256(rows) == SHA["dec-T"])
        for impl in impls:
            t0 = time.time()
            got = FR.profile(rows, N, impl)
            audit(got, N, "full/668-dec-T/%s" % impl)
            secs = time.time() - t0
            for bimpl in ("blas", "bits"):
                check("[full] H^T recomputed %-4s == banked %-4s, bin for "
                      "bin" % (impl, bimpl), got == prof[("dec-T", bimpl)],
                      "%d bins, %.0fs" % (len(got), secs))
            replayed.append("668 H^T/%s" % impl)
        ROWS.clear()
    else:
        print("\n[7] --full not requested: the banked profiles were AUDITED, "
              "not recomputed.")

    # ---------------------------------------------------------- close out
    print("\n" + "=" * 72)
    print("checks run: %d" % NCHECK[0])
    if FAIL:
        print("cert 19: FAIL (%d): %s" % (len(FAIL), FAIL))
        return 1
    print("VERDICT: the decoded order-668 record H is NOT Hadamard-")
    print("         equivalent to its own transpose -- %d of its %d bins"
          % (SEP[("dec", "dec-T")][0], NBINS[False]))
    print("         differ, in two arithmetics that agree bin for bin.")
    print("         Consequently the EIGHT matrices H, H', H*, H'' and their")
    print("         transposes are PAIRWISE inequivalent (all %d comparisons"
          % len(offdiag))
    print("         separate), so ORDER 668 CARRIES AT LEAST EIGHT HADAMARD")
    print("         EQUIVALENCE CLASSES.  LABEL: PROVEN.")
    print("         UNDER THE TRANSPOSE-EXTENDED RELATION THE COUNT IS")
    print("         UNCHANGED: exactly FOUR classes, the four of certs")
    print("         08, 13 and 15 -- each pair {X, X^T} is one class by")
    print("         definition.  Nothing here is new under that relation.")
    print("         Every profile hits C(668,4) = %d and the second moment"
          % c_n_4(N))
    print("         %d to the unit." % second_moment_want(N))
    if replayed:
        print("         PROFILE: the new leg RECOMPUTED here and matched to")
        print("         the bank (%s)." % ", ".join(replayed))
    else:
        print("         PROFILE: banked exact computation AUDITED, not")
        print("         recomputed (Hadamard-2060, exact_profile_big.py,")
        print("         desk, 2026-09-02, experiments/pr0042/")
        print("         REGISTRATION.md Amendment 2).")
    print("         NOT claimed: anything at 716, 1676, 1772 or 2060; that")
    print("         eight is the number of classes at 668; any novelty or")
    print("         priority; any general theorem about transposes.")
    print("=" * 72)
    return 0


def _audit_bank(tag, impl, p, blob, built, name_field=None):
    """The forced identities, the declared second moment, and the matrix
    binding -- against the in-process digest where this run rebuilt the
    matrix, and against the earlier certificate's pin where it did not."""
    lab = "%-7s %-4s" % (LABEL[tag], impl)
    tot, m2 = audit(p, N, "%s/%s" % (tag, impl))
    check("%s  total == C(668,4) == %d and second moment == "
          "n^3(n-1)(n-2)/24 == %d"
          % (lab, c_n_4(N), second_moment_want(N)),
          tot == c_n_4(N) and m2 == second_moment_want(N))
    if "second_moment" in blob:
        check("%s  the banked second_moment agrees" % lab,
              int(blob["second_moment"]) == m2)
    if blob.get("n", N) != N or int(blob.get("C_n_4", c_n_4(N))) != c_n_4(N):
        check("%s  banked n / C(n,4) header" % lab, False)
    declared = (blob.get(name_field) if name_field else None) or \
        blob.get("matrix_canonical_sha256") or blob.get("matrix_sha256")
    how = ("rebuilt in THIS run" if tag in REBUILT_HERE
           else "pinned by %s" % PINNED_BY[tag])
    check("%s  bank names the matrix %s" % (lab, how),
          is_sha256(declared) and declared == built[tag],
          (declared[:24] + "...") if is_sha256(declared)
          else "declared = %r" % (declared,))


if __name__ == "__main__":
    sys.exit(main())
